
module.exports = function () {
    var data = {
        // 公用 public
        "lijifuzhi":{"en": "Copy now", "zh": "立即复制"},
        "lijizhuce":{"en": "Register now", "zh": "立即注册"},
        "liaojiexiangqing": {"en": "Learn more", "zh": "了解详情"},
        "xuanzegaoshou": {"en": "Select a master", "zh": "选择高手"},
        "shouyilv": {"en": "yield rate", "zh": "收益率"},
        "fengxian": {"en": "risks", "zh": "风险"},
        "low": {"en": "low", "zh": "低"},
        "middle": {"en": "middle", "zh": "中"},
        "high": {"en": "high", "zh": "高"},
        "fuzhirenshu": {"en": "followers", "zh": "复制人数"},
        "waihui": {"en": "Foreign exchange", "zh": "外汇"},
        "guijinshu": {"en": "Precious metal", "zh": "贵金属"},
        "yuanyou": {"en": "Crude oil", "zh": "原油"},
        "faq": {"en": "FAQ", "zh": "常见问题"},

        // 底部 footer
        "foot1": {"en": "MT4 download", "zh": "MT4 下载"},

        // 首页 home
        "home1": {"en": "Follow masters' move", "zh": "复制跟单"},
        "home2": {"en": "To be an investment master", "zh": "人人都是投资高手"},
        "home3": {"en": "No need to keep an eye 24 hours", "zh": "无需24小时盯盘"},
        "home4": {"en": "Copy by one click", "zh": "一键复制"},
        "home5": {"en": "To share earnings synchronously", "zh": "立享同步收益"},
        "home6": {"en": "Enjoy ", "zh": "尊享"},
        "home7": {"en": "STP straight ", "zh": "STP直通式"},
        "home8": {"en": "trade process", "zh": "交易模式"},
        "home9": {"en": "Interlinking with many international banks", "zh": "与多家国际银行对接"},
        "home10": {"en": "Conclude a deal with the optimal price for user's order in the shortest time through STP", "zh": "通过STP方式让用户订单在最短的时间内与最优的价格成交"},
        "home11": {"en": "Grants for deposit is as much as ", "zh": "入金赠金高达"},
        "home12": {"en": "USD 10000", "zh": "10000 美金"},
        "home13": {"en": "USD 100 will be granted immediately after opening an account", "zh": "开户即可获得 100 美金"},
        "home14": {"en": "Follow masters' transaction mode and enjoy earnings synchronously", "zh": "复制高手交易，立享同步收益"},
        "home15": {"en": "Select your favorite master", "zh": "选择自己喜欢的高手"},
        "home16": {"en": " Enter the amount to be followed and then click follow", "zh": "输入复制金额，点击复制"},
        "home17": {"en": "Gain the earnings of the same proportion with the masters", "zh": "享受和高手同比例收益"},
        "home18": {"en": "To be a master, you will be granted 20% of the followers' earnings", "zh": "成为高手，您将获得复制者盈利的20%"},
        "home19": {"en": "Diversified products for transaction", "zh": "多样化的交易产品"},
        "home20": {"en": "Invest several financial products only by opening a trading account", "zh": "开设一个交易账户，轻松参与多个国际金融产品投资"},
        "home21": {"en": "Enjoy three kinds of leverages at the same time", "zh": "同时享受3种杠杆"},
        "home22": {"en": "DMA service", "zh": "市场DMA直通式报价服务"},
        "home23": {"en": "STP, safe, transparent and assured", "zh": "STP交易安全，透明，放心"},
        "home24": {"en": "High leverage, but low trading cost", "zh": "杠杆高，交易成本低"},
        "home25": {"en": "Achieve gold and silver trading by one account", "zh": "一个帐户交易黄金、白银"},
        "home26": {"en": "MT4 closely follows the trend of world financial market", "zh": "MT4 平台紧贴世界金融市场潮流"},
        "home27": {"en": "Hedging transaction reduces trading risks", "zh": "对冲交易，减少交易风险"},
        "home28": {"en": "Trading of Brent crude oil and West Texas crude oil can be achieved at the same time", "zh": "可同时操作布伦特原油和西德州原油"},
        "home29": {"en": "Enter swap processing by data smoothing method", "zh": "采用数据平滑方式进行掉期处理"},
        "home30": {"en": "Abundant products and high fund utilization rate", "zh": "产品丰富，资金利用率高"},
        "home31": {"en": "Margin level as low as 2% is offered", "zh": "提供低至2%水平的保证金水平"},
        "home32": {"en": "Low threshold and transparent quotation", "zh": "门槛较低，报价透明"},
        "home33": {"en": "STP (straight trade process)", "zh": "STP直通式交易模式"},
        "home34": {"en": "Provide guarantee for excellent trading experience and optimizing user value", "zh": "为出色的交易体验和优化用户价值提供保障"},
        "home35": {"en": "By cooperation with many famous institutions, TigerWit makes use of the foreign exchange quotation and settlement from many international banks and transmits user's order to the international banking market through STP, thus contributing to conclusion of a deal with the optimal price for user's order in the shortest time.", "zh": "TigerWit老虎金融与多家知名机构合作，从多家国际银行等获得外汇报价和清算，并且通过STP的方式将用户的订单传输到国际间银行市场，从而让用户订单在最短的时间内与最优的价格成交。"},
        "home36": {"en": "Why to choose TigerWit", "zh": "为什么选择TigerWit老虎金融"},
        "home37": {"en": "TigerWit will render a very distinctive trading experience for users after an account is opened", "zh": "开立老虎金融账户，享受与众不同的交易体验"},
        "home38": {"en": "Stable MT4 platform", "zh": "稳定的MT4平台"},
        "home39": {"en": "Conclusion of a deal in milliseconds and high stability and safety ensure top-level trading experience", "zh": "毫秒交易速度，稳定安全，保障顶级交易体验"},
        "home40": {"en": "One-to-one customer service", "zh": "一对一客服服务"},
        "home41": {"en": "One-to-one customer support and VIP professional services", "zh": "一对一客服支持，VIP级专业服务"},
        "home42": {"en": "Leverage utilization", "zh": "杠杆利用"},
        "home43": {"en": "50-times, 100-times and 200-times leverage trading satisfies users demands in risk control and capital management in a flexible way", "zh": "50倍、100倍、200倍杠杆交易，灵活满足您对风险控制，资金管理的需求"},
        "home44": {"en": "Instant deposit and withdrawal", "zh": "闪电出入金"},
        "home45": {"en": "Instant transfer of deposit to account and of withdrawal within 24h", "zh": "入金即时到账，出金24小时到账"},
        "home46": {"en": "TigerWit-everyone is an investment master", "zh": "老虎金融 — 人人都是投资高手"},
        "home47": {"en": "The secret of successful investment does not lie in the social influence and development prospect of a certain industry, but in a company's competitive edges and the sustainability of such edges. Only everlasting and profound product and service superiorities can generate generous returns for investors.", "zh": "投资的秘诀、不是评估某一行业对社会的影响有多大、或它的发展前景有多好、而是一间公司有多强的竞争优势、这优势可以维持多久。产品和服务的优越性持久而深厚、才能给投资者带来优厚的回报。"},
        "home48": {"en": "-Warren Buffett", "zh": "—— 沃伦·巴菲特"},
        "home49": {"en": "", "zh": ""},
        "home50": {"en": "", "zh": ""}
    };

    return data;
}; 