
module.exports = function () {
    var data = {
        // 公用 public
        "lijifuzhi":{"en": "Copy now", "zh": "立即复制"},
        "fuzhi":{"zh": "复制", "en": "Copy"},
        "lijizhuce":{"en": "Register now", "zh": "立即注册"},
        "liaojiexiangqing": {"en": "Learn more", "zh": "了解详情"},
        "xuanzegaoshou": {"en": "Select a master", "zh": "选择高手"},
        "shouyilv": {"en": "yield rate", "zh": "收益率"},
        "zongshouyilv": {"en": "Total Return", "zh": "总收益率"},
        "fengxian": {"en": "risks", "zh": "风险"},
        "low": {"en": "low", "zh": "低"},
        "middle": {"en": "middle", "zh": "中"},
        "high": {"en": "high", "zh": "高"},
        "fuzhirenshu": {"en": "Copiers", "zh": "复制人数"},
        "zuidifuzhijine": {"en": "MIN copy", "zh": "最低复制金额"},
        "zoushitu": {"en": "Trend Chart", "zh": "走势图"},
        "zuidahuiche": {"en": "MAX drawdown", "zh": "最大回撤"},
        "waihui": {"en": "Foreign exchange", "zh": "外汇"},
        "guijinshu": {"en": "Precious metal", "zh": "贵金属"},
        "yuanyou": {"en": "Crude oil", "zh": "原油"},
        "faq": {"en": "FAQ", "zh": "常见问题"},
        "login": {"en": "Login", "zh": "登录"},
        "register": {"en": "Register", "zh": "注册"},
        "signout": {"en": "sign out", "zh": "退出"},
        "password": {"en": "Password", "zh": "密码"},
        "username": {"en": "Username", "zh": "昵称"},
        "phone": {"en": "Phone", "zh": "手机号码"},
        "email": {"en": "E-mail", "zh": "电子邮箱"},
        "verifycode": {"en": "Verification code", "zh": "验证码"},

        // 导航栏 navbar
        "navbar1": {"en": "Homepage", "zh": "首页"},
        "navbar2": {"en": "Master", "zh": "复制跟单"},
        "navbar3": {"en": "Follow master's trace", "zh": "高手跟单"},
        "navbar4": {"en": "Follow masters' move regularly", "zh": "定期跟单"},
        "navbar5": {"en": "Products", "zh": "产品介绍"},
        "navbar6": {"en": "Foreign Exchange Transaction", "zh": "外汇交易"},
        "navbar7": {"en": "Crude oil trading", "zh": "原油交易"},
        "navbar8": {"en": "Precious metals trading", "zh": "贵金属交易"},
        "navbar9": {"en": "Contracts for differences", "zh": "差价合约"},
        "navbar10": {"en": "About Tiger", "zh": "关于老虎"},
        "navbar11": {"en": "About TigerWit", "zh": "关于老虎金融"},
        "navbar12": {"en": "STP", "zh": "STP交易模式"},
        "navbar13": {"en": "", "zh": ""},

        // 底部 footer
        "foot1": {"en": "Instruments of exchange", "zh": "交易工具"},
        "foot2": {"en": "MT4 download", "zh": "MT4 下载"},
        "foot3": {"en": "MT4 web version", "zh": "MT4 网页版"},
        "foot4": {"en": "Learning Center", "zh": "学习中心"},
        "foot5": {"en": "The Basics", "zh": "基础知识"},
        "foot6": {"en": "Learning video", "zh": "学习视频"},
        "foot7": {"en": "Conditions and clauses", "zh": "条件和条款"},
        "foot8": {"en": "Risk Disclosure Statement", "zh": "风险披露书"},
        "foot9": {"en": "Declaration by Client", "zh": "客户声明"},
        "foot10": {"en": "Trading Notes for User", "zh": "用户交易须知"},
        "foot11": {"en": "Contact Us", "zh": "联系我们"},
        "foot12": {"en": "The margined transaction in financial market is full of higher risk and not suitable for all investors, and rising leverage means the coexistence of high risk and high profits. Before making deals, it is necessary to take your investment goals, investment experience and risk tolerance into prudent consideration and select the right investment style; and you need to learn that there are possibilities of all or part of losses in margined transaction in financial market. TigerWit transaction platform provides trade leaders and common investors with copy information from websites and service, including real-time transaction prompt, investment articles and other resources from internet, and all clients need to think over and weigh investment risk and security. The historical transaction data of trade leaders doesn’t stand for their operational capacity in the future, and clients need to take any risk on their own.", "zh": "高风险投资警告:金融市场的保证金交易存在较高风险，不适合所有投资者，增大杠杆意味着高风险与高收益并存。在您决定交易前，应当谨慎考虑您的投资目标、投资经验及风险承受能力，并选择适合自己的投资方式；您需要知晓金融市场的保证金交易具有全部或部分亏损的可能。老虎金融交易平台为广大交易高手及普通投资者提供复制交易服务，网站发布的任何信息，包括实时交易提醒、投资文章及其他资源等均来自互联网所有用户需仔细考量并权衡投资风险及安全性。交易高手的历史交易数据不代表未来操作能力，用户因此所产生的任何风险需自己承担。"},

        // 首页 home
        "home1": {"en": "Follow masters' move", "zh": "复制跟单"},
        "home2": {"en": "To be an investment master", "zh": "人人都是投资高手"},
        "home3": {"en": "No need to keep an eye 24 hours", "zh": "无需24小时盯盘"},
        "home4": {"en": "Copy by one click", "zh": "一键复制"},
        "home5": {"en": "To share earnings synchronously", "zh": "立享同步收益"},
        "home6": {"en": "Enjoy ", "zh": "尊享"},
        "home7": {"en": "STP straight ", "zh": "STP直通式"},
        "home8": {"en": "trade process", "zh": "交易模式"},
        "home9": {"en": "Interlinking with many international banks", "zh": "与多家国际银行对接"},
        "home10": {"en": "Conclude a deal with the optimal price for user's order in the shortest time through STP", "zh": "通过STP方式让用户订单在最短的时间内与最优的价格成交"},
        "home11": {"en": "Grants for deposit is as much as ", "zh": "入金赠金高达"},
        "home12": {"en": "USD 10000", "zh": "10000 美金"},
        "home13": {"en": "USD 100 will be granted immediately after opening an account", "zh": "开户即可获得 100 美金"},
        "home14": {"en": "Follow masters' transaction mode and enjoy earnings synchronously", "zh": "复制高手交易，立享同步收益"},
        "home15": {"en": "Select your favorite master", "zh": "选择自己喜欢的高手"},
        "home16": {"en": " Enter the amount to be followed and then click follow", "zh": "输入复制金额，点击复制"},
        "home17": {"en": "Gain the earnings of the same proportion with the masters", "zh": "享受和高手同比例收益"},
        "home18": {"en": "To be a master, you will be granted 20% of the followers' earnings", "zh": "成为高手，您将获得复制者盈利的20%"},
        "home19": {"en": "Diversified products for transaction", "zh": "多样化的交易产品"},
        "home20": {"en": "Invest several financial products only by opening a trading account", "zh": "开设一个交易账户，轻松参与多个国际金融产品投资"},
        "home21": {"en": "Enjoy three kinds of leverages at the same time", "zh": "同时享受3种杠杆"},
        "home22": {"en": "DMA service", "zh": "市场DMA直通式报价服务"},
        "home23": {"en": "STP, safe, transparent and assured", "zh": "STP交易安全，透明，放心"},
        "home24": {"en": "High leverage, but low trading cost", "zh": "杠杆高，交易成本低"},
        "home25": {"en": "Achieve gold and silver trading by one account", "zh": "一个帐户交易黄金、白银"},
        "home26": {"en": "MT4 closely follows the trend of world financial market", "zh": "MT4 平台紧贴世界金融市场潮流"},
        "home27": {"en": "Hedging transaction reduces trading risks", "zh": "对冲交易，减少交易风险"},
        "home28": {"en": "Trading of Brent crude oil and West Texas crude oil can be achieved at the same time", "zh": "可同时操作布伦特原油和西德州原油"},
        "home29": {"en": "Enter swap processing by data smoothing method", "zh": "采用数据平滑方式进行掉期处理"},
        "home30": {"en": "Abundant products and high fund utilization rate", "zh": "产品丰富，资金利用率高"},
        "home31": {"en": "Margin level as low as 2% is offered", "zh": "提供低至2%水平的保证金水平"},
        "home32": {"en": "Low threshold and transparent quotation", "zh": "门槛较低，报价透明"},
        "home33": {"en": "STP (straight trade process)", "zh": "STP直通式交易模式"},
        "home34": {"en": "Provide guarantee for excellent trading experience and optimizing user value", "zh": "为出色的交易体验和优化用户价值提供保障"},
        "home35": {"en": "By cooperation with many famous institutions, TigerWit makes use of the foreign exchange quotation and settlement from many international banks and transmits user's order to the international banking market through STP, thus contributing to conclusion of a deal with the optimal price for user's order in the shortest time.", "zh": "TigerWit老虎金融与多家知名机构合作，从多家国际银行等获得外汇报价和清算，并且通过STP的方式将用户的订单传输到国际间银行市场，从而让用户订单在最短的时间内与最优的价格成交。"},
        "home36": {"en": "Why to choose TigerWit", "zh": "为什么选择TigerWit老虎金融"},
        "home37": {"en": "TigerWit will render a very distinctive trading experience for users after an account is opened", "zh": "开立老虎金融账户，享受与众不同的交易体验"},
        "home38": {"en": "Stable MT4 platform", "zh": "稳定的MT4平台"},
        "home39": {"en": "Conclusion of a deal in milliseconds and high stability and safety ensure top-level trading experience", "zh": "毫秒交易速度，稳定安全，保障顶级交易体验"},
        "home40": {"en": "One-to-one customer service", "zh": "一对一客服服务"},
        "home41": {"en": "One-to-one customer support and VIP professional services", "zh": "一对一客服支持，VIP级专业服务"},
        "home42": {"en": "Leverage utilization", "zh": "杠杆利用"},
        "home43": {"en": "50-times, 100-times and 200-times leverage trading satisfies users demands in risk control and capital management in a flexible way", "zh": "50倍、100倍、200倍杠杆交易，灵活满足您对风险控制，资金管理的需求"},
        "home44": {"en": "Instant deposit and withdrawal", "zh": "闪电出入金"},
        "home45": {"en": "Instant transfer of deposit to account and of withdrawal within 24h", "zh": "入金即时到账，出金24小时到账"},
        "home46": {"en": "TigerWit-everyone is an investment master", "zh": "老虎金融 — 人人都是投资高手"},
        "home47": {"en": "The secret of successful investment does not lie in the social influence and development prospect of a certain industry, but in a company's competitive edges and the sustainability of such edges. Only everlasting and profound product and service superiorities can generate generous returns for investors.", "zh": "投资的秘诀、不是评估某一行业对社会的影响有多大、或它的发展前景有多好、而是一间公司有多强的竞争优势、这优势可以维持多久。产品和服务的优越性持久而深厚、才能给投资者带来优厚的回报。"},
        "home48": {"en": "-Warren Buffett", "zh": "—— 沃伦·巴菲特"},
        "home49": {"en": "", "zh": ""},
        "home50": {"en": "", "zh": ""},

        // 产品介绍－外汇交易 forex
        "forex1": {"en": "Foreign exchange transaction involves buying and/or selling a kind of foreign currency. In terms of the largest single product market in the world, trades valuing over USD 5 trillion are achieved on the current foreign exchange market. The foreign exchange and price is mainly influenced by international trade, economy and policies of countries and investment flow direction and the foreign exchange market is featured as transparent information, tremendous turnover and great fairness and transparency.", "zh": "外汇交易涉及买入一个外国货币和/或卖出另一个外国货币。全球最大的单一产品市场，当今外汇市场每天拥有超过5万亿美元的成交额，外汇市场和价格主要受国际间的交易，各国经济和政策以及投资流向的影响，外汇市场信息透明，流通量巨大，公平透明。"},
        "forex2": {"en": "According to the investigation report of BIS (bank of international settlement), over USD 5 trillion of daily trading volume was concluded in global foreign exchange market in 2014.", "zh": "根据BIS（bank of international settlement）的调查报告显示，在 2014 年，全球外汇市场日交易量已经达到了 5 万亿美金以上"},
        "forex3": {"en": "Why to trade foreign exchange in TigerWit?", "zh": "为什么在 TigerWit 老虎金融交易外汇"},
        "forex4": {"en": "TigerWit keeps a close watch on global market through STP. With simple, quick, efficient and safe cash depositing and withdraw mode, TigerWit renders services of all major currency pairs and cross currency pairs. With the provision of more flexible, transparent and competitive foreign exchange agreement, TigerWit also provides the most creative order following mode and serves as a bond to link investment masters and common investors. ", "zh": "TigerWit 老虎金融，采用STP直通式交易，紧盯全球市场。简单快捷高效安全的出入金方式，涵盖所有主流货币对及交叉货币对。我们提供更灵活，更透明，更具竞争力的外汇合约，同时您还可以享受到 TigerWit 老虎金融最具创新性的跟单交易模式，是连结高手和普通投资者纽带。"},
        "forex5": {"en": "TigerWit's advantages in foreign exchange trading", "zh": "在TigerWit 老虎金融交易外汇的优势"},
        "forex6": {"en": "4 kinds of leverage are offered.", "zh": "同时享受 4 种杠杆"},
        "forex7": {"en": "50-times, 100-times and 200-times and 400-times leverage trading satisfies users demands in risk control and capital management in a flexible way. ", "zh": "我们同时提供 50 倍，100 倍，200 倍，400 倍四种不同的杠杆，更灵活的满足您对于风险把控，资金管理的需求。"},
        "forex8": {"en": "PS: Individual application shall be made for 400-times leverage. ", "zh": "PS：400 倍杠杆需要单独申请。"},
        "forex9": {"en": "Follow masters' move", "zh": "复制跟单交易"},
        "forex10": {"en": "TigerWit provides the most advanced and most creative full-automatic order following system and gathers numerous investment masters with great profit-making capabilities. The investors can gain the earnings of the same proportion with the masters through following them. Masters can also gain more earnings through increasing their followers continuously.", "zh": "TigerWit 老虎金融提供业内最先进，最具创新性的全自动复制跟单系统，并且汇聚众多颇具盈利能力的投资高手，投资者可通过复制高手交易获得同比例投资收益。高手也可通过不断增加跟随者而获得更多收益。"},
        "forex11": {"en": "Market ECN straight quotation service", "zh": "市场 ECN 直通式报价服务"},
        "forex12": {"en": "Through cooperation with many top banks and financial institutions in the industry, TigerWit directly obtains the optimal quotation of more than 20 banks to clients through ECN mode, such as Morgan, Citibank, BAC and Buckley. ", "zh": "TigerWit 老虎金融与业内顶级银行及金融机构合作，采取 ECN 模式直接获取多达 20 多家银行如摩根，花旗，美银，巴克利等等国际巨头见最优报价提供给尊敬的客户。"},
        "forex13": {"en": "Trading time", "zh": "交易时间段"},
        "forex14": {"en": "TigerWit offers global trading and also provides financial services for clients continuously except the necessary inter-bank maintenance period per day.", "zh": "老虎金融提供全球交易，除去每日必要的银行间维护时段，不间断的为我们的客户提供金融服务。"},
        "forex15": {"en": "How to achieve foreign exchange trade in TigerWit?", "zh": "在 TigerWit 老虎金融怎么做外汇交易?"},
        "forex16": {"en": "An investor of TigerWit sold one lot (eur/usd) around 10:00 on October 22, platform time of TigerWit at the position of 1.13450 by USD1000. ", "zh": "某位老虎金融的投资者在 TigerWit 的平台时间 10 月 22 号 10 点左右，于 1.13450 位置左右动用 1000 美金卖出 1 手欧美（eur/usd）。"},
        "forex17": {"en": "On the second day, the trade was closed at the position of 1.1100 around 10:00 on October 23. ", "zh": "到了第二日，10 月 23 日 10 点左右，于 1.1100 位置平仓了结，"},
        "forex18": {"en": "The earnings obtained by the client is (1.13450-1.1100)*100000=USD2450, ", "zh": "客户收益（1.13450-1.1100）*100000=2450 美元，"},
        "forex19": {"en": "the yield rate of which is 245%.", "zh": "收益率 245%。"},
        "forex20": {"en": "Introduction to TigerWit currency pairs", "zh": "TigerWit 老虎金融货币对介绍"},
        "forex21": {"en": "Product code", "zh": "产品代码"},
        "forex22": {"en": "Chinese name", "zh": "中文名称"},
        "forex23": {"en": "Point difference", "zh": "点差"},
        "forex24": {"en": "average point difference", "zh": "平均点差"},
        "forex25": {"en": "Leverage", "zh": "杠杆"},
        "forex26": {"en": "Quoted price", "zh": "报价位"},
        "forex27": {"en": "Minimum trading volume", "zh": "最小交易量"},
        "forex28": {"en": "Per standard lot", "zh": "每标准手"},
        "forex29": {"en": "Contract volume", "zh": "合约量"},
        "forex30": {"en": "Trading time", "zh": "交易时间"},
        "forex31": {"en": "Five digits after the decimal point", "zh": "小数点后五位"},
        "forex32": {"en": "Three digits after the decimal point", "zh": "小数点后三位"},
        "forex33": {"en": "Floating point difference", "zh": "浮动点差"},
        "forex34": {"en": "24h quotation on trading day", "zh": "交易日24小时报价"},
        "forex35": {"en": "Trading period:", "zh": "交易时段"},
        "forex36": {"en": "TigerWit also provides the trading products of cross currency pairs of the above major currency pairs.", "zh": "TigerWit老虎金融同时提供以上主流货币对的交叉货币对交易产品"},
        
        // 产品介绍－原油交易 oil
        "oil1": {"en": "Acting a strategic role for industry and cornerstone of modern civilization, crude oil is one of the largest commodities in global trade and also one of the most important trading subjects in global financial assets. ", "zh": "工业的血液，现代文明的基石，也是全球贸易中最大宗的商品之一，全球金融资产中最重要的交易标的物之一。"},
        "oil2": {"en": "Why to trade crude oil in TigerWit?", "zh": "为什么在 TigerWit 老虎金融原油交易"},
        "oil3": {"en": "In addition to Brent crude oil and West Texas crude oil, both of which sees the largest trading volume in the world, TigerWit also provides US natural gas contracts. TigerWit wholeheartedly provides the clients with the most flexible leverage, the most competitive point difference advantages and also obtains the most direct quotation data sources from world-leading banks in the financial sector. Meanwhile, it also renders the most innovative order following system.", "zh": "TigerWit 老虎金融除了提供两大全球交易量最大的原油：布伦特原油和西德州原油合约以外，同时提供美国天然气合约。TigerWit 老虎金融竭诚为客户提供最灵活的杠杆，最具竞争性的点差优势，来源于全球金融界顶级银行的最直接的报价数据源。同时也提供最具创新性的跟单系统服务。"},
        "oil4": {"en": "Advantages of TigerWit in crude oil trading", "zh": "在 TigerWit 老虎金融做原油交易的优势"},
        "oil5": {"en": "Hedging transaction reduces trading risks", "zh": "对冲交易，减少交易风险"},
        "oil6": {"en": "Two major kinds of tradable crude oils at present are Brent crude oil and West Texas crude oil, for which hedging transaction can also be realized. In case of price distortion, low-risk arbitrage opportunity would be sought.", "zh": "目前可以进行交易的两大原油为：布伦特原油和西德州原油，并且这 2 种原油可以进行对冲交易，发现价格扭曲，寻找低风险套利机会。"},
        "oil7": {"en": "Low margin but high earnings", "zh": "保证金低，收益高"},
        "oil8": {"en": "The trading leverage of crude oil in TigerWit is as high as 50 times, thus consuming less margin. As a result, less investment cost is required, while the leverage can double that of the spot crude oil in China. The formula mode of international spot crude oil per ton is roughly USD 50 *current rate / (converted by 1000*weights and measures), while the cost formula mode of domestic spot crude oil is point difference + current price * 0.12%", "zh": "在 TigerWit 老虎金融做原油交易杠杆高达 50 倍以上，占用保证金更低。所以 TigerWit 老虎金融所需的投资成本更低，而杠杆可超过国内现货原油的一倍以上。国际现货原油的成本折合到每吨的计算方式是：50 美金左右 * 当日汇率 / (1000 * 度量衡折换)。而国内现货原油的陈本计算方式是：点差 + 当日价格 * 0.12% 。"},
        "oil9": {"en": "No commission charge", "zh": "无手续费"},
        "oil10": {"en": "No commission charge will be required for crude oil in TigerWit and only point difference will be charged. One lot is equivalent to about USD 50, equaling to 1000 barrels. Then 7.5 barrels equals to 1ton. Thus, it is converted as USD 0.37 /ton, equivalent to RMB 2.3/ton.", "zh": "在 TigerWit 老虎金融做原油交易是不收取手续费的，仅收取点差，一手 50 美金左右等于 1000 桶，那 7.5 桶等于 1 吨，因此我们的折合到吨就是 0.37 美金/吨，差不多就是 2.3 人民币/吨。"},
        "oil11": {"en": "Easy loss stop", "zh": "止损简便"},
        "oil12": {"en": "Loss can be stopped by only one-time setting, which will remain effective on the following day, by which losses caused by forgetting setting will be greatly reduced.", "zh": "TigerWit 老虎金融可以做到只需设置一次止损，隔天仍然有效，这样很大程度上避免了因忘记设置止损产生的亏损。"},
        "oil13": {"en": "Enter swap processing by data smoothing method.", "zh": "采用数据平滑方式进行掉期处理"},
        "oil14": {"en": "Through cooperation with the most authoritative data provider, TigerWit applies the most advanced data smoothing mode in case of swap extension in dominant contract of international crude oil without water loss fees, rather than mandatory liquidation and position opening in China.", "zh": "TigerWit 老虎金融与业内最权威的数据提供商合作，在国际原油主力合约发生掉期展期时，采用最先进的数据平滑处理，而非国内原油采用的强行平仓，开仓，无掉水费用。"},
        "oil15": {"en": "Follow masters' move", "zh": "复制跟单交易"},
        "oil16": {"en": "For green-hand investors in crude oil trading, the move of the masters in crude oil trading can be followed directly, through which earnings of the same proportion can be realized and the trading risks of beginner investors are also reduced.", "zh": "针对于一些对原油交易不熟悉的投资者，可选择原油交易的高手直接复制，即可同比例盈利，降低了初级投资者的交易风险。"},
        "oil17": {"en": "How to achieve crude oil trade in TigerWit?", "zh": "在TigerWit 老虎金融怎么做原油交易？"},
        "oil18": {"en": "An investor of TigerWit sold one lot of West Texas crude oil (xti/usd) around 15:00 on October 23, platform time of TigerWit at the position of 45.890 by USD 1000.", "zh": "某位老虎金融的投资者在 TigerWit 的平台时间 10 月 23 号 15 点左右，于 45.890位置左右动用 1000 美金卖出 1 手西德州原油（xti/usd）。"},
        "oil19": {"en": "Around one hour later, the trade was closed at the position of 44.50 around 16:00 on October 23.", "zh": "一个多小时后，10 月 23 日 16 点左右，于 44.50 位置平仓了结，"},
        "oil20": {"en": "The earnings obtained by the client is (45.89-44.50)*1000=USD1390, ", "zh": "客户收益（45.89-44.50）*1000=1390 美元，"},
        "oil21": {"en": "the yield rate of which is 139%.", "zh": "收益率 139%。"},
        "oil22": {"en": "Introduction to TigerWit energy products", "zh": "TigerWit 老虎金融能源类交易产品介绍"},
        "oil23": {"en": "Product code", "zh": "产品代码"},
        "oil24": {"en": "Chinese name", "zh": "中文名称"},
        "oil25": {"en": "Contract volume", "zh": "合约量"},
        "oil26": {"en": "Measurement unit", "zh": "计量单位"},
        "oil27": {"en": "Minimum contract unit (standard lot)", "zh": "最小合约单位(标准手)"},
        "oil28": {"en": "Maximum trading volume (lot)", "zh": "最大交易量(手)"},
        "oil29": {"en": "Commission charge ($)", "zh": "手续费($)"},
        "oil30": {"en": "Trading time (MT4 platform time)", "zh": "交易时间(MT4平台时间)"},
        "oil31": {"en": "Quotation closing time (platform time)", "zh": "报价关闭时间(平台时间)"},
        "oil32": {"en": "Product introduction", "zh": "产品简介"},
        "oil33": {"en": "MBTU", "zh": "百万英国热量单位"},
        "oil34": {"en": "barrels", "zh": "桶"},
        "oil35": {"en": "USD", "zh": "美元"},
        "oil36": {"en": "01:00 on Monday - 23:55 on Friday", "zh": "周一01:00-周五23:55"},
        "oil37": {"en": "00:00-01:00 of platform time per day", "zh": "每日平台时间00:00-01:00"},
        "oil38": {"en": "As for energy contract taking NYMEX US natural gas products as the benchmark, natural gas satisfies about 1/4 energy demands of the US and can also be used as hedging tool for such products as electricity option.", "zh": "以NYMEX交易所美国天然气产品为基准的能源合约，天然气提供了美国四分之一左右的能源需求，同时可作为电力期权等产品的对冲工具"},
        "oil39": {"en": "Desulfurized light crude oil contract with NYMEX US crude oil as the benchmark is one of the two crude oil benchmarking products in the world and is applied by many countries as the pricing datum of crude oil products, which is also the energy contract with the largest trading volume in the world.", "zh": "以NYMEX交易所美国原油为基准的脱硫轻质原油合约，是全球两大原油基准产品之一，被用于多国原油产品的定价基准。也是世界上交易量最大的能源合约"},
        "oil40": {"en": "Commonly known as North Sea oil, which is also desulfurized light crude oil. Pricing datum of crude oil in Europe and one of the two major crude oil benchmarking products in the world, which can also be applied as hedging product against West Texas crude oil", "zh": "即是俗称的北海油，同样是脱硫轻质原油。是欧洲地区的原油定价基准，也是全球两大原油基准产品之一，可以用于与西德州原油进行对冲的产品"},
        
        // 产品介绍－贵金属交易 metal
        "metal1": {"en": "As the most ancient, most traditional and most widely recognized currency symbol, precious metals fall into the category of traditional safe-haven assets, which occupy an important position in industrial manufacture and have both the property and commodity property of safe-haven currencies. ", "zh": "作为人类文明最古老的最传统最被广泛认可的货币符号，属于传统的避险资产，同时随着科技的进步，也在工业生产中占据了重要的地位，同时具有避险货币的属性与商品属性 。"},
        "metal2": {"en": "What is spot gold and silver trading? ", "zh": "什么是现货黄金、白银交易"},
        "metal3": {"en": "Margin trade of spot gold and silver is also known as London gold and silver exchange. London gold and silver per standard lot is 100 ounces and 5000 ounces separately. What is different from New York gold futures period is spot gold. Swap and extension are not needed for spot silver. Meanwhile, contract value and leverage are more flexible and the fund utilization rate is much higher. ", "zh": "现货黄金与现货白银保证金交易亦称之为伦敦金，伦敦银。每标准手伦敦金为 100 盎司，每标准手白银为 5000 盎司，与纽约期金期银不同的是现货金，现货银无需掉期，展期，同时合约大小，杠杆更为灵活，资金利用率更高。"},
        "metal4": {"en": "TigerWit's advantages in foreign exchange trading", "zh": "在 TigerWit 老虎金融交易黄金、白银的优势"},
        "metal5": {"en": "High leverage", "zh": "杠杆高"},
        "metal6": {"en": "TigerWit offers three kinds of leverage for flexible option and the leverage of spot silver is as high as 150 times.", "zh": "TigerWit 老虎金融提供三种杠杆灵活选择，现货白银杠杆可高达 150 倍以上。"},
        "metal7": {"en": "Low trading cost", "zh": "交易成本低"},
        "metal8": {"en": "The cost of trading spot silver in TigerWit is as low as USD 200 /155 kg, equivalent to RMB 7.5 /kg. ", "zh": "TigerWit 老虎金融交易现货白银成本低至约 200 美元/155 kg，约 7.5 人民币/千克。"},
        "metal9": {"en": "Low threshold", "zh": "门槛较低"},
        "metal10": {"en": "RMB 300 margin will be needed for spot silver trading in China, while the minimum trading margin for spot silver trading in TigerWit is as low as USD 10. ", "zh": "国内现货白银交易动用保证金为约为 300 人民币，而 TigerWit 老虎金融现货白银交易最小交易保证金仅为 10 美金。"},
        "metal11": {"en": "Achieve gold and silver trading by one account", "zh": "一个帐户交易黄金、白银"},
        "metal12": {"en": "Given the restrictions of China's national conditions, most domestic exchanges can only trade spot silver but fail to trade gold. However, gold products fall into the trade category of greater importance in the international market. Given such situations, TigerWit can provide both silver and gold trading, rendering more independent choices for investors.", "zh": "由于国内相关国情限制，国内大多数交易所仅能交易现货白银，而无法交易现货黄金，但黄金产品是国际市场上更为关注与重要的交易品种，而 TigerWit 老虎金融同时提供白银与黄金交易，给广大投资者更为自主的选择。"},
        "metal13": {"en": "Trading by MT4", "zh": "使用 MT4 交易"},
        "metal14": {"en": "TigerWit has adopted the most extensively used and mature MT4 platform in the world and launched intelligent trading module, closely following the trend of world financial market.", "zh": "TigerWit 老虎金融采用全球使用最广泛的成熟的 MT4 平台，开放智能交易模块，紧贴世界金融市场潮流。"},
        "metal15": {"en": "Follow masters' move", "zh": "复制跟单交易"},
        "metal16": {"en": "TigerWit provides the most advanced and most creative full-automatic order following system and gathers numerous investment masters with great profit-making capabilities. The investors can gain the earnings of the same proportion with the masters through following them. Masters can also gain more earnings through increasing their followers continuously.", "zh": "TigerWit 老虎金融提供业内最先进，最具创新性的全自动复制跟单系统，并且汇聚众多颇具盈利能力的投资高手，投资者可通过复制高手交易获得同比例投资收益。高手也可通过不断增加跟随者而获得更多收益。"},
        "metal17": {"en": "Introduction to TigerWit precious metal products", "zh": "TigerWit 老虎金融贵金属交易产品介绍"},
        "metal18": {"en": "Product code", "zh": "产品代码"},
        "metal19": {"en": "Chinese name", "zh": "中文名称"},
        "metal20": {"en": "Point difference", "zh": "点差"},
        "metal21": {"en": "average point difference", "zh": "平均点差"},
        "metal22": {"en": "Leverage", "zh": "杠杆"},
        "metal23": {"en": "Quoted price", "zh": "报价位"},
        "metal24": {"en": "Minimum trading lots", "zh": "最小交易手数"},
        "metal25": {"en": "Contract volume per standard lot", "zh": "每标准手合约量"},
        "metal26": {"en": "Trading time", "zh": "交易时间"},
        "metal27": {"en": "Two digits after the decimal point", "zh": "小数点后两位"},
        "metal28": {"en": "Three digits after the decimal point", "zh": "小数点后三位"},
        "metal29": {"en": "ounces", "zh": "盎司"},
        "metal30": {"en": "Trading period on the trading day", "zh": "交易日交易时段"},

        // 产品介绍－股指，差价合约 cfd
        "cfd1": {"en": "Stock index", "zh": "股指"},
        "cfd2": {"en": "Contracts for differences", "zh": "差价合约"},
        "cfd3": {"en": "Stock index is short for stock price index, which is prepared by stock exchanges or financial service institutions to indicate the fluctuation of stock market quotation for investors' reference. Stock price index is developed to describe the overall price change on the stock market. The index is acquired by selecting a group of representative stocks, achieving the weighted average by their prices and then by certain calculation programming.", "zh": "股指是股票价格指数简称，股票价格指数即股票指数。是由证券交易所或金融服务机构编制的表明股票行市变动的一种供参考的指示数字。股票价格指数是描述股票市场总的价格水平变化的指标。它是选取有代表性的一组股票，把他们的价格进行加权平均，通过一定的计算得到。"},
        "cfd4": {"en": "Contracts for Difference (CFD) can reflect the price changes of stock or index and offer the profits or losses caused by price changes. Moreover, actual possession of stock or index futures is not necessary. Contracts for difference is the most familiar trading tool to Chinese residents and in Reuter's Financial Glossary it is defined as trading mode in which exchange of physical commodities or securities is not involved and only the balance between settlement price and contract price is used for cash settlement.", "zh": "差价合约（Contracts for Difference ，CFD）可以反映股票或指数的价格变化并提供价格变动所带来的盈利或亏损，而无须实际拥有股票或指数期货。差价合约是目前国内居民听说过的最多的一种交易工具，路透金融词典中对差价合约的定义如下：泛指不涉及实物商品或证券的交换、仅以结算价与合约价的差额作现金结算的交易方式。"},
        "cfd5": {"en": "TigerWit's advantages in stock index and contracts for difference", "zh": "在 TigerWit 老虎金融做股指、差价合约的优势"},
        "cfd6": {"en": "Extensive products", "zh": "产品丰富"},
        "cfd7": {"en": "TigerWit offers the trading categories on global mainstream stock markets, including such mainstream stock index products as US Dollar Index, Nikkei and European blue chip index.", "zh": "TigerWit 老虎金融提供全球主流股市交易品种，包含三大美指，日经，欧洲优选等等主流股指产品。"},
        "cfd8": {"en": "High fund utilization rate", "zh": "资金利用率高"},
        "cfd9": {"en": "Margin level as low as 2% is offered", "zh": "提供低至 2% 水平的保证金水平。"},
        "cfd10": {"en": "Low threshold", "zh": "门槛较低"},
        "cfd11": {"en": "The extremely low entry threshold enables investors to take part without need of tens of thousands of dollars that are needed by stock index futures.", "zh": "入市门槛极低，无需如股指期货般需要数万美元计的入市门槛。"},
        "cfd12": {"en": "Transparent quotation", "zh": "报价透明"},
        "cfd13": {"en": "TigerWit provides the first-hand quotation from top banks, thus help investors achieve price discovering.", "zh": "TigerWit 老虎金融提供来自于顶级银行的第一手数据报价，帮助投资者以进行价格发现。"},
        "cfd14": {"en": "Follow masters' move", "zh": "复制跟单交易"},
        "cfd15": {"en": "TigerWit provides the most advanced and most creative full-automatic order following system and gathers numerous investment masters with great profit-making capabilities. The investors can gain the earnings of the same proportion with the masters through following them. Masters can also gain more earnings through increasing their followers continuously.", "zh": "TigerWit 老虎金融提供业内最先进，最具创新性的全自动复制跟单系统，并且汇聚众多颇具盈利能力的投资高手，投资者可通过复制高手交易获得同比例投资收益。高手也可通过不断增加跟随者而获得更多收益。"},
        "cfd16": {"en": "How to achieve stock index trade in TigerWit?", "zh": "在 TigerWit 老虎金融怎么做股指交易?"},
        "cfd17": {"en": "An investor of TigerWit bought one lot of European blue chip index (eustx50) around 10:00 on October 22, platform time of TigerWit at the position of 3260 by EUR 65.", "zh": "某位老虎金融的投资者在 TigerWit 的平台时间 10 月 22 号 10 点左右，于 3260 位置左右动用 65 欧元买入 1 手欧洲绩优指数（eustx50）。"},
        "cfd18": {"en": "On the second day, the trade was closed at the position of 3440 around 14:00 on October 23.", "zh": "到了第二日，10 月 23 日 14 点左右，于 3440 位置平仓了结，"},
        "cfd19": {"en": "The earnings obtained by the client is 3440-3260= EUR 180, ", "zh": "客户收益 3440-3260=180 欧元，"},
        "cfd20": {"en": "the yield rate of which is 180/65/100%=276%. ", "zh": "收益率 180/65/100%=276%。"},
        "cfd21": {"en": "Introduction to TigerWit financial stock index", "zh": "TigerWit 老虎金融股指产品介绍"},
        "cfd22": {"en": "Product code", "zh": "产品代码"},
        "cfd23": {"en": "Chinese name", "zh": "中文名称"},
        "cfd24": {"en": "Contract volume", "zh": "合约量"},
        "cfd25": {"en": "Contract margin (USD)", "zh": "合约保证金(美元)"},
        "cfd26": {"en": "Minimum contract unit (standard lot)", "zh": "最小合约单位(标准手)"},
        "cfd27": {"en": "Maximum trading volume (lot)", "zh": "最大交易量(手)"},
        "cfd28": {"en": "Trading time (MT4 platform time)", "zh": "交易时间(MT4平台时间)"},
        "cfd29": {"en": "Quotation closing time (platform time)", "zh": "报价关闭时间(平台时间)"},
        "cfd30": {"en": "Product introduction", "zh": "产品简介"},
        "cfd31": {"en": "lot", "zh": "手"},
        "cfd32": {"en": "contract", "zh": "合约"},
        "cfd33": {"en": "Daylight saving time: 04:50 on Monday - 00:00 on Saturday", "zh": "夏令时:周一04:50-周六00:00"},
        "cfd34": {"en": "Winter time: 01:50 on Monday - 23:00 on Friday", "zh": "冬令时:周一01:50-周五23:00"},
        "cfd35": {"en": "per day", "zh": "每日"},
        "cfd36": {"en": "on Monday", "zh": "周一"},
        "cfd37": {"en": "on Friday", "zh": "周五"},
        "cfd38": {"en": "on Saturday", "zh": "周六"},
        "cfd39": {"en": "Platform time per day", "zh": "每日平台时间"},
        "cfd40": {"en": "Stock index of 200 largest enterprises in Australia, greatly influenced by China's economy.", "zh": "澳大利亚200家最大企业股票指数，受中国经济状况影响较大"},
        "cfd41": {"en": "Also known as European blue chip index in Euro zone", "zh": "也称欧洲绩优指数，欧元区蓝筹股股价指数"},
        "cfd42": {"en": "Index of earnings obtained from 30 kinds of listed blue chip stock indexes in German.", "zh": "德国30种法兰克福上市蓝筹股票指数经过算法后得出收益的指数"},
        "cfd43": {"en": "Index of 225 stocks listed in Tokyo Stock Exchange", "zh": "日经225只东京交易所上市股票指数"},
        "cfd44": {"en": "Index based on tech stock", "zh": "基于高科技股票的指数"},
        "cfd45": {"en": "Benchmark index for major exchanges of Spain ", "zh": "西班牙主要交易所的基准指数"},
        "cfd46": {"en": "Index of 100 listed stocks in London Stock Exchange", "zh": "伦敦交易所上市100支股票指数"},
        "cfd47": {"en": "Stock index of 30 major industrial enterprises of USA", "zh": "美国30家主要工业公司构成的股票指数"},
        "cfd48": {"en": "Stock index of 500 leading enterprises in USA", "zh": "美国500家领军企业构成的股票指数"},
        "cfd49": {"en": "Hang Seng Midcap 50 Index (HK50) is acquired from the weighted average of the market value of 50 largest enterprises listed in Hong Kong Stock Exchange. The index includes 60% market value and involves well-known enterprises, such as HSBC Group, China Construction Bank and China Mobile", "zh": "香港恒生 50 指数（HK50）由香港股票交易所上市的 50 家最大的上市公司的市值加权而得。该指数囊括 60% 的市值并包含了赫赫有名的公司，诸如汇丰集团、中国建设银行和中国移动"},

        // 关于老虎－关于老虎金融 about
        "about1": {"en": "About us", "zh": "关于我们"},
        "about2": {"en": "As a leader in social investing, TigerWit has independently developed China's first Internet foreign exchange product and attracted numerous trading elites to gather here to render services for investors by virtue of its abundant capital and rich experience in financial industry as well as innovation capability in Internet products. Relying on TigerWit, common investors can follow the trading system and follow the masters' trading order automatically to gain the earnings of the same proportion with the masters. All will grow to be an investment master. ", "zh": "TigerWit老虎金融社交投资引领者，凭借雄厚的资本，结合丰富的金融行业阅历与互联网产品创新能力，自主研发了国内第一款互联网外汇产品，吸引了众多顶尖的交易精英汇聚在此，普通投资者可通过复制交易系统，自动复制高手的交易订单，同比例获得盈利。在这里人人都是投资高手。"},
        "about3": {"en": "Join hands with dozens of world's top banks", "zh": "与数十家全球顶级银行合作"},
        "about4": {"en": "TigerWit provides nearly 100 kinds of foreign exchange, precious metal and index trading products. One account is offered with three different kinds of leverage simultaneously. The user's order can be directly butted with dozens of world's top banks through STP (including Bank of America, Citibank, JPMorgan Chase & Co, Barclays and Macquarie Bank), ensuring fair and transparent trading and rendering top-class trading experience for all traders. ", "zh": "TigerWit老虎金融提供近百种外汇、贵金属和指数交易品种，一个账户更可同时享受3种不同的交易杠杆，用户的交易订单通过STP模式直接与数十家全球顶级银行（包括：美国银行，花旗，摩根大通，巴克莱，麦格理银行等）对接，保证交易的公正与透明，为广大交易者提供一流交易体验。"},
        "about5": {"en": "Bank of America is the first and largest commercial bank in terms of capital. In 2006, the bank ranked No.3 according to Forbes 2000 and is the second oldest bank in USA. ", "zh": "美国银行以资产计是美国第一大商业银行；2006年，根据《福布斯》2000年排名是世界第三大公司，是美国第二个历史最悠久的银行。"},
        "about6": {"en": "BNP PARIBAS has set over 700 offices and branches in 85 countries and regions, offering services for more than 80 of 100 large international enterprises. ", "zh": "法国巴黎银行在全球85个国家和地区拥有700多个办事处，为100家国际大型企业中的80多家提供服务。"},
        "about7": {"en": "United Bank of Switzerland (UBS for short) is the largest financial holding group in Europe. ", "zh": "瑞士联合银行集团（United Bank of Switzerland，中文简称瑞银集团）是欧洲最大的金融控股集团。"},
        "about8": {"en": "TigerWit investor-Tang Binsen", "zh": "老虎金融投资人——唐彬森"},
        "about9": {"en": "He, born after 1980, is the principal owner of Happy Farm that has been popular for several years after its release and an entrepreneur building up a fortune from overseas market. In 2012, together with his team, he rolled out the first oversea-oriented navigation web and antivirus software developed by a Chinese and also received a cordial reception from President Hu Jintao at the 90th anniversary of the Communist Youth League as an excellent youth delegate. In 2015, the independently developed clash of kings by his company ranked No.6 in the North American bestsellers' list and became an intern game achieving the greatest outcomes in the internationalization process of China's games. Such outstanding achievements are gained exactly by an obscure company founded in a basement of Beihang University by Tang who also serves as the CEO of Elex. He is a legendary figure in creating overseas market for China's games. ", "zh": "他是那款一经发行便走红数年的《开心农场》的大当家；他是80后从海外市场起家的创业者；2012年，他带领团队推出了中国人首款面向海外的导航网和杀毒软件服务，同年作为优秀青年代表在建团90周年获得胡锦涛总书记亲切接见；2015年，他旗下的自研游戏clash of kings拿下北美畅销榜第6名，成为中国游戏国际化历史流水最高的游戏。谁也没想到，一个曾经在北航地下室成立的名不见经传的公司，能够拥有现在如此骄人的成就。他是谁？他就是智明星通首席执行官唐彬森。一个创造中国游戏海外市场的传奇人物。"},
        
        // 关于老虎－stp交易模式 stp
        "stp1": {"en": "What is STP?", "zh": "STP是什么？"},
        "stp2": {"en": "In STP (straight through processing), user's order is transmitted to an international bank through the transaction client to obtain the optimal transaction price, that is after the order of the client is sent to the bank, approximately real-time trading will be made based on the price of the bank. ", "zh": "STP（straight through processing ），是指用户的订单通过交易客户端传达到国际间银行，并且获得最优成交价的模式，即客户的下单发送到银行，按银行的价位接近即时交易。"},
        "stp3": {"en": "STP trading advantages of TigerWit ", "zh": "TigerWit 老虎金融STP交易优势"},
        "stp4": {"en": "Through cooperation with several famous institutions, TigerWit obtains foreign exchange quotation and settlement from Barclays Bank, Macquarie Bank, Deutsche Bank, JPMorgan Chase & Co, and Bank of America and transmits the user's order to the international bank market through STP, thus enabling the user to conclude a deal with the optimal price for user's order in the shortest time.", "zh": "TigerWit老虎金融与多家知名机构合作，从巴克莱银行，麦格理银行，德意志银行，摩根大通，花旗银行，美国银行等获得外汇报价和清算，并且通过STP的方式将用户的订单传输到国际间银行市场，从而让用户订单在最短的时间内与最优的价格成交。"},
        "stp5": {"en": "National banks Investment banks Large retail banks Large hedge funds ECN system", "zh": "国家银行 投资银行 大型零售银行 大型对冲基金 ECN系统"},
        "stp6": {"en": "Quotation integration", "zh": "报价整合"},
        "stp7": {"en": "Bridge", "zh": "桥"},
        "stp8": {"en": "MT4 server", "zh": "MT4服务器"},
        "stp9": {"en": "MT4 client", "zh": "MT4客户端"},
        "stp10": {"en": "TigerWit", "zh": "TigerWit老虎金融"},
    };

    return data;
}; 