;
(function () {
    'use strict';

    angular.module('fullstackApp').factory('langData', langData);

    langData.$inject = ['$cookies'];

    function langData ($cookies) {
        var language = 'zh';
        var companyConfig = {
            companyNickName: "tigerwit",
            companyNameZh: "TigerWit",
            companyNameEn: "TigerWit",
            telephone: "400 - 809 - 8509",
            mt4Live: "TigerWit-Live",
            companyCopyRules: "https://www.tigerwit.com/web/copy/rules",
            webSite:"www.tigerwit.com",
        };
        
        angular.forEach($cookies, function (value, index) {

            if (index === 'lang') {
                // console.info(value, index);
                language = value === 'en' ? value : 'zh';

            }
            if (index === 'company_name') {
                if (value === 'lonfx') {
                    companyConfig = {
                        companyNickName: "lonfx",
                        companyNameZh: "莱恩",
                        companyNameEn: "lonfx",
                        telephone: "xxxx-xxx",
                        mt4Live: "TigerWit-Live",
                        companyCopyRules: "https://lonfx.tigerwit.com/web/copy/rules",
                        webSite:"lonfx.tigerwit.com",
                    };
                }
                if (value === 'pandafx') {
                    companyConfig = {
                        companyNickName: "pandafx",
                        companyNameZh: "熊猫外汇",
                        companyNameEn: "pandafx",
                        telephone: "xxxx-xxx",
                        mt4Live: "TigerWit-Live",
                        companyCopyRules: "https://pandafx.tigerwit.com/web/copy/rules",
                        webSite:"pandafx.tigerwit.com",
                    };
                }
                if (value === 'pkds') {
                    companyConfig = {
                        companyNickName: "pkds",
                        companyNameZh: "派克道森",
                        companyNameEn: "Pakerdawson",
                        telephone: "400 - 900 - 9296",
                        mt4Live: "Parkerdawson-Live",
                        companyCopyRules: "http://www.pkdsfx.com/web/copy/rules",
                        webSite:"www.pkdsfx.com",
                    };
                }
            } 
        });

        var data = {

            "companyCopyRules": {"zh": companyConfig.companyCopyRules, "en": companyConfig.companyCopyRules},
            "companyNameEn": {"zh":companyConfig.companyNameEn, "en": companyConfig.companyNameEn},
            "companyNameZh": {"zh":companyConfig.companyNameZh, "en": companyConfig.companyNameZh},
            "telephone": {"zh": companyConfig.telephone, "en": companyConfig.telephone},
            "mt4Live": {"zh": companyConfig.mt4Live, "en": companyConfig.mt4Live},
            "webSite": {"zh": companyConfig.webSite, "en": companyConfig.webSite},

            "company": companyConfig.companyNickName,
            "language": language,
            // 公用 public
            "lijifuzhi":{"en": "Copy now", "zh": "立即复制"},
            "fuzhi":{"zh": "复制", "en": "Copy"},
            "lijizhuce":{"en": "Register now", "zh": "立即注册"},
            "liaojiexiangqing": {"en": "Learn more", "zh": "了解详情"},
            "xuanzegaoshou": {"en": "Select a master", "zh": "选择高手"},
            "shouyilv": {"en": "yield rate", "zh": "收益率"},
            "zongshouyilv": {"en": "Total Return", "zh": "总收益率"},
            "fengxian": {"en": "risks", "zh": "风险"},
            "low": {"en": "low", "zh": "低"},
            "middle": {"en": "middle", "zh": "中"},
            "high": {"en": "high", "zh": "高"},
            "fuzhirenshu": {"en": "Copiers", "zh": "复制人数"},
            "lishifuzhirenshu": {"en": "Historical Copiers", "zh": "历史复制人数"},
            "zuidifuzhijine": {"en": "MIN copy", "zh": "最低复制金额"},
            "zoushitu": {"en": "Trend Chart", "zh": "走势图"},
            "zuidahuiche": {"en": "MAX drawdown", "zh": "最大回撤"},
            "waihui": {"en": "Foreign exchange", "zh": "外汇"},
            "guijinshu": {"en": "Precious metal", "zh": "贵金属"},
            "yuanyou": {"en": "Crude oil", "zh": "原油"},
            "faq": {"en": "FAQ", "zh": "常见问题"},
            "login": {"en": "Login", "zh": "登录"},
            "register": {"en": "Register", "zh": "注册"},
            "signout": {"en": "sign out", "zh": "退出"},
            "password": {"en": "Password", "zh": "密码"},
            "username": {"en": "Username", "zh": "昵称"},
            "phone": {"en": "Phone", "zh": "手机号码"},
            "email": {"en": "E-mail", "zh": "电子邮箱"},
            "verifycode": {"en": "Verification code", "zh": "验证码"},

            // 复制跟单 ranklist
            "rank1": {"en": "Ranking", "zh": "综合排名"},

            // 登录 login
            "login1": {"en": "Mobile No.", "zh": "手机号码"},
            "login2": {"en": "Please enter your account No.", "zh": "请输入账号"},
            "login3": {"en": "xx", "zh": "账号格式不正确"},
            "login4": {"en": "xx", "zh": "账号尚未注册"},
            "login5": {"en": "Please enter your password", "zh": "请输入密码"},
            "login6": {"en": "Log in automatically next time", "zh": "下次自动登陆"},
            "login7": {"en": "Forgot password", "zh": "忘记密码"},
            "login8": {"en": "SSL login is adopted in "+companyConfig.companyNameEn+" and data transmission is safe.", "zh": "您在"+companyConfig.companyNameZh+"登录采用 SSL 登录方式数据传输安全"},
            "login9": {"en": "Login", "zh": "登 录"},
            "login10": {"en": "Register", "zh": "注 册"},
            "login11": {"en": "Login...", "zh": "登录中"},
            "login12": {"en": "Login too much, please try again after 5 minutes", "zh": "登录次数过多，请 5 分钟后重试"},
            "login13": {"en": "account No. or password is wrong", "zh": "用户名或者密码错误"},
            "login14": {"en": "xx", "zh": "账号已注销"},

            // 注册 register
            "register1": {"en": "Register an account", "zh": "注册账户"},
            "register2": {"en": "Real name certification", "zh": "实名认证"},
            "register3": {"en": "KYC authentication", "zh": "KYC 认证"},
            "register4": {"en": "Registration done", "zh": "完成注册"},
            "register5": {"en": "Confirm password", "zh": "确认密码"},
            "register6": {"en": "Obtain verification code", "zh": "获取验证码"},
            "register7": {"en": "Please enter username", "zh": "请输入昵称"},
            "register8": {"en": "Please enter your phone", "zh": "请输入手机号码"},
            "register9": {"en": "Please enter the verification code", "zh": "请输入验证码"},
            "register10": {"en": "Please enter your e-mail", "zh": "请输入电子邮箱"},
            "register11": {"en": "Please enter your password", "zh": "请输入密码"},
            "register12": {"en": "Please re-enter your password", "zh": "请再次输入密码"},
            "register13": {"en": "Registration means that you have agreed the relevant regulations", "zh": "注册即同意"},
            "register14": {"en": "Risk Disclosure Statement", "zh": "风险披露书"},
            "register15": {"en": "Declaration by Client", "zh": "客户声明"},
            "register16": {"en": "Trading Notes for Users", "zh": "用户交易须知"},
            "register17": {"en": "Register in 30s and open the journey to fortune", "zh": "30 秒注册 开启财富之旅"},
            "register20": {"en": "Register now to receive $200", "zh": "立即注册 领取$1000"},
            "register18": {"en": "Registered?", "zh": "已有账户？"},
            "register19": {"en": "Log in now", "zh": "立即登录"},

            // 复制跟单-数据统计 traderSummary
            "traderSummary1": {"en": "Summary", "zh": "交易概况"},
            "traderSummary2": {"en": "Accuracy", "zh": "准确率"},
            "traderSummary3": {"en": "Margin Cost", "zh": "最大保证金占用"},
            "traderSummary4": {"en": "Profit", "zh": "盈利订单"},
            "traderSummary5": {"en": "Lose", "zh": "亏损订单"},
            "traderSummary6": {"en": "Close Out", "zh": "平仓交易"},
            "traderSummary7": {"en": "Avg. Holding time", "zh": "平均持仓时间"},
            "traderSummary8": {"en": "Avg. Trades/Month", "zh": "月平均交易次数"},
            "traderSummary9": {"en": "Profitable/Month", "zh": "月回报率"},
            "traderSummary10": {"en": "Max Drawdown", "zh": "最大回撤"},
            "traderSummary11": {"en": "Largest Profit Spread", "zh": "最大盈利点差"},
            "traderSummary12": {"en": "Total Return", "zh": "总收益率"},
            "traderSummary13": {"en": "Trading Chart", "zh": "交易走势图"},
            "traderSummary14": {"en": "Main Symble", "zh": "主要交易品种"},
            "traderSummary15": {"en": "No Data", "zh": "无数据"},

            // 复制跟单-当前交易 HoldingTrades
            "HoldingTrades1": {"en": "Operation", "zh": "操作"},
            "HoldingTrades2": {"en": "Openning Price", "zh": "开仓价"},
            "HoldingTrades3": {"en": "Current Price", "zh": "现价"},
            "HoldingTrades4": {"en": "Holding Time", "zh": "持仓时间"},
            "HoldingTrades5": {"en": "Spread", "zh": "点数"},
            "HoldingTrades6": {"en": "Profit", "zh": "收益"},
            "HoldingTrades7": {"en": "Sell", "zh": "买跌"},
            "HoldingTrades8": {"en": "Buy", "zh": "买涨"},
            "HoldingTrades9": {"en": "No Data", "zh": "无数据"},
            "HoldingTrades10": {"en": "Note：Trades won't be shown here before 7 days.", "zh": "注：当前交易仅显示高手最近一周持仓订单"},
            "HoldingTrades11": {"en": "en", "zh": "zh"},
            
            // 复制跟单-历史交易 TradingHistory
            "TradingHistory1": {"en": "Operation", "zh": "操作"},
            "TradingHistory2": {"en": "Openning Price", "zh": "开仓价"},
            "TradingHistory3": {"en": "Closing Price", "zh": "平仓价"},
            "TradingHistory4": {"en": "Holding Time", "zh": "持仓时间"},
            "TradingHistory5": {"en": "Spread", "zh": "点数"},
            "TradingHistory6": {"en": "Profit", "zh": "收益"},
            "TradingHistory7": {"en": "Sell", "zh": "买跌"},
            "TradingHistory8": {"en": "Buy", "zh": "买涨"},
            "TradingHistory9": {"en": "No Data", "zh": "无数据"},
            "TradingHistory10": {"en": "ago", "zh": "前"},
            "TradingHistory11": {"en": "en", "zh": "zh"},

            // login 新版登录
            actLogin1: {zh: "快捷登录", en: "Fast Login"},
            actLogin2: {zh: "账号密码登录", en: "Password Login"},
            actLogin3: {zh: "请输入手机号码", en: "Please Type in the Phone Number"},
            actLogin4: {zh: "请输入验证码", en: "Verification Code"},
            actLogin5: {zh: "获取验证码", en: "Send SMS"},
            actLogin6: {zh: "后重新获取", en: "after resend"},
            actLogin7: {zh: "记住登录状态", en: "Remember login status"},
            actLogin8: {zh: "登录", en: "Login"},
            actLogin9: {zh: "未注册TigerWit的手机号，登录时将自动注册", en: "Logging in will turn to registration if the Phone Number hasn't been registered."},
            actLogin10: {zh: "提交代表您已阅读并同意", en: "I accept the"},
            actLogin11: {zh: "客户协议", en: "Client Agreement"},
            actLogin12: {zh: "风险披露声明", en: "Risk Disclosure"},
            actLogin13: {zh: "隐私政策", en: "Privacy Policy"},
            actLogin14: {zh: "法律声明", en: "Legal Notices"},
            actLogin15: {zh: "及其他", en: "and other"},
            actLogin16: {zh: "请输入正确的手机号码", en: "Please Type in the correct Phone Number"},
            actLogin17: {zh: "手机号", en: "Phone"},
            actLogin18: {zh: "校验码", en: "Verification Code"},
            actLogin19: {zh: "请填写完整信息", en: "Please Type in the complete information"},
            actLogin20: {zh: "设置密码", en: "Set Password"},
            actLogin21: {zh: "请输入密码", en: "Please Type in the Password"},
            actLogin22: {zh: "密码", en: "Password"},
            actLogin23: {zh: "请为您的账户设置密码，6-15位字母、数字或符号组合", en: "Please set a password for your account，6-15 bit of Letters, numbers, or combinations of symbols"},
            actLogin24: {zh: "请输入您的账号", en: "Please Type in the Phone Number"},
            actLogin25: {zh: "请输入您的账户密码", en: "Please Type in the Password"},
            actLogin26: {zh: "忘记密码", en: "Forget the Password?"},
            actLogin27: {zh: "*已使用SSL加密技术保护您的网络安全", en: "Secure your network with SSL encryption technology"},
            actLogin28: {zh: "找回密码", en: "Retrieve the password"},
            actLogin29: {zh: "下一步", en: "Next"},
            actLogin29_1: {zh: "上一步", en: "Prev"},
            actLogin30: {zh: "完成修改", en: "Submit"},
            actLogin31: {zh: "新密码设置成功", en: "The new password is set up successfully"},
            actLogin32: {zh: "重新登录", en: "Re-register"},
            actLogin33: {zh: "完成注册", en: "Complete"},
            actLogin34: {zh: "跳过", en: "Jump Over"},
            actLogin35: {zh: "", en: ""},
            actLogin36: {zh: "", en: ""},
            actLogin37: {zh: "账号或手机号", en: "Account / Phone No"},
            actLogin38: {zh: "请输入您的账号或手机号", en: "Enter account / phone No"},

            // 通行证个人中心
            tigerWitID: {
                title: {zh: "通行证账号", en: "TigerWitID"},
                // 账户概况
                myAccount:{
                    title: {zh: "账户概况", en: "My Account"},
                    totalAssets: {zh: "资产总额", en: "Total Assets"},
                    totalLots: {zh: "总交易手数", en: "Total Lots"},
                    totalEarnings: {zh: "总盈利", en: "Total Earnings"},
                    totalProfitRate: {zh: "总收益率", en: "Total Profit Rate"},
                    tradingAccount: {zh: "交易账户", en: "Trading account"},
                    upgradeToLiveAccount: {zh: "升级到真实账户", en: "Upgrade to a live account"},
                    wallet: {zh: "钱包", en: "Wallet"},
                    unactivated: {zh: "未激活", en: "Unactivated"},
                    deposit: {zh: "充值", en: "DEPOSIT"},
                    withdrawal: {zh: "提现", en: "WITHDRAWAL"},
                    exit: {zh: "退出", en: "EXIT"},
                },
                // 交易账户
                tradingAccount: {
                    title: {zh: "交易账户", en: "Trading Account"},
                    totalAssets: {zh: "资产总额", en: "Total Assets"},
                    totalLots: {zh: "总交易手数", en: "Total Lots"},
                    totalEarnings: {zh: "总盈利", en: "Total Earnings"},
                    totalProfitRate: {zh: "总收益率", en: "Total Profit Rate"},
                    tradingSubAccounts: {zh: "交易子账户", en: "Trading sub-accounts"},
                    createAccount: {zh: "新建账号", en: "Create account"},
                    becomeMaster: {zh: "申请高手", en: "Become a master"}, // 有待商讨
                    netAssetValue: {zh: "资产净值", en: "Net asset value"},
                    floatingPL: {zh: "浮动盈亏", en: "Floating P/L"},
                    marginLevel: {zh: "保证金比例", en: "Margin level"},
                    depositToActivate: {zh: "充值激活账户", en: "Deposit to activate the account"}, // 若字段太长去掉the account
                },
                // 详情
                details: {
                    title: {zh: "详情", en: "Details"},
                    netAssetValue: {zh: "资产净值", en: "Net asset value"},
                    freeMargin: {zh: "可用保证金", en: "Free margin"},
                    marginLevel: {zh: "保证金比例", en: "Margin level"},
                    totalLots: {zh: "总交易手数", en: "Total Lots"},
                    historicalTotalEarning: {zh: "历史总收益", en: "Historical total earning"},
                    floatingPL: {zh: "浮动盈亏", en: "Floating P/L"},
                    totalProfitRate: {zh: "总收益率", en: "Total Profit Rate"},
                    currentTrading: {zh: "当前交易", en: "Current Trading"},
                    deducted20Note: {zh: "注：您复制高手的盈利部分将会扣除20%作为佣金给高手。详情请参考：", en: "Note：The 20% profit that you gain by following the master will be deducted as commission. Please refer to:"},
                    operation: {zh: "操作", en: "Operation"},
                    openPrice: {zh: "开仓价", en: "Open price"},
                    currentPrice: {zh: "现价", en: "Current price"},
                    profit: {zh: "收益", en: "Profit"},
                    autonomousTransaction: {zh: "自主交易", en: "Autonomous transaction"},
                    lots: {zh: "交易量", en: "Lots"},
                    fundsOccupying: {zh: "资金占用", en: "Funds Occupying"},
                    P_L: {zh: "订单盈亏", en: "P/L"},
                    swap: {zh: "库存费", en: "Swap"},
                    commission: {zh: "手续费", en: "Commission"},
                    profitRate: {zh: "收益率", en: "Profit Rate"},
                    investedFunds: {zh: "投入资金", en: "Invested Funds"},
                },
                historyTransactions: {
                    title: {zh: "历史交易", en: "History Transactions"},
                    operation: {zh: "操作", en: "Operation"},
                    lots: {zh: "交易手数", en: "Lots"},
                    profit: {zh: "收益", en: "Profit"},
                    autonomousTransaction: {zh: "自主交易", en: "Autonomous Transaction"},
                },
                dataStatistics: {
                    title: {zh: "数据统计", en: "Data statistics"},
                    transactionsProfile: {zh: "交易概况", en: "Transactions profile"},
                    closedOrders: {zh: "平仓交易", en: "Closed Orders"},
                    profitOrders: {zh: "盈利订单", en: "Profit Orders"},
                    lossOrders: {zh: "亏损订单", en: "Loss Orders"},
                    avgHoldingTime: {zh: "平均持仓时间", en: "Avg Holding Time"},
                    maximumDrawdown: {zh: "最大回撤", en: "Maximum Drawdown"},
                    avgNumberTransactionsPerMonth: {zh: "月平均交易次数", en: "Avg Number of Transactions per Month"},
                    maximumProfitMargin: {zh: "最大盈利点差", en: "Maximum Profit Margin"},
                    monthlyRateReturn: {zh: "月回报率", en: "Monthly Rate of Return"},
                    totalProfitRate: {zh: "总收益率", en: "Total Profit Rate"},
                    tradingChart: {zh: "交易走势图", en: "Trading Chart"},
                    profitRate: {zh: "收益率", en: "Profit Rate"},
                    mainTradingSymbols: {zh: "主要交易品种", en: "Main Trading Symbols"},
                },
                fundRecords: {
                    title: {zh: "资金记录", en: "Fund Records"},
                },
                wallet: {
                    title: {zh: "钱包", en: "Wallet"},
                    details: {zh: "查看明细", en: "Details"},
                    manageBankCards: {zh: "管理银行卡", en: "Manage Bank Cards"},
                    addBankCards: {zh: "添加银行卡", en: "Add Bank Cards"},
                },
                coupon: {
                    title: {zh: "我的红包", en: "Coupon"},
                    available: {zh: "可用红包", en: "Available"},
                    records: {zh: "红包记录", en: "Records"},
                    automaticReceive: {zh: "自动领取红包", en: "Automatic Receive"},
                    exchangeValidUntil: {zh: "兑换有效期截止", en: "Exchange valid until"},
                },
                inviteFriends: {
                    title: {zh: "邀请好友", en: "Invite Friends"},
                    inviteFriend: {zh: "邀请好友，赢取10美元", en: "Invite a friend and win 10 dollar"},
                    invitedFriends: {zh: "当前邀请人数", en: "Invited Friends"},
                    inviteFriendsRegulations: {zh: "邀请好友规则", en: "Invite Friends Regulations"},
                    tip1: {zh: "1、注册即获得邀请类红包“人从众”，邀请3名好友注册，且至少有1人入金并完成1手交易即可兑现, 每位用户仅可领取一次；", en: "1. A reward coupon will be delivered to your account when you registered, it can be cashed once you invited three friends and at least one of them deposited and had one lot transaction."},
                    tip2: {zh: "2、您只有通过邀请链接进行注册的好友才算有效；", en: "2. It can be effective only when your friend is registered by the invite link."},
                    tip3: {zh: "3、同一手机号，身份证号和银行卡号视为同一用户；", en: "3.Same cellphone, ID and bank card number will be treated as same user."},
                    tip4: {zh: "4、任何通过第三方作弊软件刷取好友邀请奖励，一经发现TigerWit有权取消红包兑现奖励；", en: "4.Tigerwit have the right to cancel the coupon reward once boost invite rewards by third party cheating software was found."},
                    tip5: {zh: "5、本活动最终解释权归TigerWit所有。如有疑问，请咨询客服 400 - 809 - 8509。", en: "5.TigerWit reserve all the right for the final explanation. If you have any questions, please contact our customer service center 400-809-8509."},
                    nameFriend: {zh: "好友昵称", en: "Name of friend"},
                    statusDeposit: {zh: "入金状态", en: "Status in deposit"},
                    statusTransactions: {zh: "是否完成交易", en: "Status in transactions"},
                },
                settings: {
                    title: {zh: "账户设置", en: "Settings"},
                    general: {zh: "基本信息", en: "General"},
                    userName: {zh: "用户名", en: "User Name"},
                    modify: {zh: "修改", en: "Modify"},
                    country: {zh: "国家", en: "Country"},
                    setPhotos: {zh: "修改头像", en: "Set Photos"},
                    choosePhoto: {zh: "选择头像", en: "Choose a Photo"},
                    onlySupport : {zh: "只支持 jpg、png 格式且大小在 2MB 以内", en: "Only support JPG, PNG format and size within 2MB"},
                    security: {zh: "账户安全", en: "Security"},
                    passwordManagement: {zh: "密码管理", en: "Password Management"},
                    oldPassword: {zh: "原密码", en: "Old password"},
                    newPassword: {zh: "新密码", en: "New password"},
                    confirmNewPassword: {zh: "确认新密码", en: "Confirm new password"},
                    phoneNumberSettings: {zh: "手机号码设置", en: "Phone number settings"},
                    boundPhoneXXX: {zh: "您已经绑定了手机号", en: "You have now bound phone number xxx"},
                    newPhoneNumber: {zh: "新手机号码", en: "New phone number"},
                    verificationCode: {zh: "验证码", en: "Verification code"},
                    getVerificationCode: {zh: "获取验证码", en: "Get verification code"},
                    mailboxSettings: {zh: "电子邮箱设置", en: "Mailbox settings"},
                    notificationActivateWallet: {zh: "激活零钱包提示", en: "Notification of activate the wallet"},
                    notificationActivateWalletCon: {zh: "零钱包不支持单独激活，交易类账户开通成功后，零钱包将自动激活。", en: "The wallet does not support individual activation, it will be activated automatic when trading account was opened."},
                    openLiveAccount: {zh: "开通真实账户", en: "Open a Live Account"},
                    openLiveAccountTip1: {zh: "开户即得$200交易红包，入金可获$800红包！", en: "Open a live account and receive a $200 coupon, deposit and receive $800 coupon."},
                    openLiveAccountTip2: {zh: "同时享受更多交易体验：", en: "You will enjoy more transaction experiences at the same time："},
                    openLiveAccountTip3: {zh: "自由交易，享受灵活杠杆", en: "Freely trading, flexible lever."},
                    openLiveAccountTip4: {zh: "复制高手获得收益", en: "Get profit by following masters."},
                    openLiveAccountTip5: {zh: "申请成为高手获得盈利分成", en: "Apply for a master and obtain commissions."},
                    freeOpening: {zh: "免费开通", en: "Free Opening"},
                    openExperienceAccount: {zh: "开通体验金账户", en: "Open an experience account"},
                    openExperienceAccountTip1: {zh: "开户即送$2000交易体验金。", en: "Open the experience account and receive a $2000 virtual balance."},
                    openExperienceAccountTip2: {zh: "只需一步，即刻享受", en: "Just one step, and you will enjoy:"},
                    openExperienceAccountTip3: {zh: "自由交易，灵活杠杆", en: "Freely trading, flexible lever."},
                    openExperienceAccountTip4: {zh: "不用承担任何风险", en: "Take no risk."},
                },
                date: {zh: "日期", en: "Date"},
                types: {zh: "全部类型", en: "Types"},
                amount: {zh: "金额", en: "Amount"},
                state: {zh: "状态", en: "State"},
                balance: {zh: "余额", en: "Balance"},
                delete: {zh: "删除", en: "Delete"},
                copy: {zh: "复制", en: "Copy"},
                noData: {zh: "无数据", en: "No data"},
                submit: {zh: "提交", en: "SUBMIT"},
                confirm: {zh: "确定", en: "Submit"},
            },
        };

        return data;
    }
})();