;(function () {
  var page = $(".bd_forextrading").attr("data-lang-page");
  var pageInfo = {
    english: {
      open_account: "Open an account",
      live_account: "Open a live account",
      demo_account: "Demo account",
      navbar_home: "Home",
      navbar_traders: "Traders",
      navbar_partners: "Partners",
      home_title1: "Trading made simple, copy-trade a Master.",
      home_title2: "Join the 250,000+ traders",
      home_title3: "on TigerWit.",
      home_cont1: "Follow a Master to copy their trades and access global Foreign Exchange markets on our smart, simple and intuitive app.",
      home_cont2: "The key to an exciting new world of trading possibilities, for the simple and transparent experience every trader deserves. ",
      home_cont3: "Open a Live account to access the world’s most traded financial markets or you can open a Demo account to practice your trading skills on our smart, innovative and easy to use app.",
      home_cont4: "Trading CFDs involves risk and can result in loss of your capital.",
      home_title4: "Follow",
      home_title5: "a Master",
      home_cont5: "TigerWit Masters are selected and ranked based on their performance and trading strategies.",
      home_cont6: "Follow in the footsteps of a Master trader and",
      home_cont7: "replicate their strategies",
      home_cont8: "with just a single click.",
      home_cont9: "Get started and download the app",
      home_title6: "Become",
      home_title7: "a Master",
      home_cont10: "Become a TigerWit Master and",
      home_cont11: "earn 20% commission",
      home_cont12: "on your follower’s trades.",
      home_cont13: "Get started and download the app",
      home_title8: "Download the app today",
      traders_title1: "It doesn’t matter if a trader is",
      traders_title2: "experienced or new with TigerWit",
      traders_title3: "We have combined cutting-edge technology with convenience to ensure",
      traders_title4: "users can access global markets on a simple, sophisticated app that’s tailored",
      traders_title5: "for all traders. Our copy-trading options, and competitive Master trader",
      traders_title6: "commissions are accessible, transparent and simple.",
      traders_cont1: "Trade FX globally",
      traders_cont2: "Your choice of markets, the way you want to trade",
      traders_cont3: "Innovative, easy to follow copy-trading options",
      traders_cont4: "SCB and FCA regulated",
      traders_cont5: "Efficient cash depositing and withdrawal mode",
      traders_cont6: "Powered by blockchain",
      partners_title1: "We build strong partnerships",
      partners_title2: "and long-term relationships",
      partners_cont1: "Being a TigerWit partner means being part of a global company that develops long-term relationships and celebrates the success of your clients. ",
      partners_cont2: "No other trading platform has our secure and innovative blockchain trading ledger, which is available to your clients on an intuitive, easy to use app.",
      partners_join: "Join us",
      partners_block1_1: "Simple account",
      partners_block1_2: "management",
      partners_block1_3: "functions on an",
      partners_block1_4: "easy to use app",
      partners_block2_1: "Exclusive promotions",
      partners_block2_2: "with our partner",
      partners_block2_3: "Liverpool FC",
      partners_block3_1: "Blockchain",
      partners_block3_2: "based distributed",
      partners_block3_3: "trading ledger",
      partners_block4_1: "Advance agency",
      partners_block4_2: "support plan",
      partners_block4_3: "24/5 client and",
      partners_block4_4: "technology support",
      partners_block5_1: "SCB and FCA",
      partners_block5_2: "regulated"
    },
    indonesia: {
      open_account: "Buka Akun",
      live_account: "Buka Akun Live",
      demo_account: "Akun Demo",
      navbar_home: "Beranda",
      navbar_traders: "Trader",
      navbar_partners: "Mitra",
      home_title1: "Trading jadi lebih mudah, copy-trade Master.",
      home_title2: "Ayo bergabung dengan 250.000++",
      home_title3: "trader di TigerWit.",
      home_cont1: "Anda dapat mengikuti dan menyalin setiap transaksi Master kami sekaligus memiliki akses ke pasar pertukaran Mata Uang terbesar di dunia melalui aplikasi kami yang pintar, mudah digunakan dan berintuitif tinggi",
      home_cont2: "Bersama kami, anda akan menemukan berbagai peluang menarik di dunia trading, terutama dari segi transparansi yang sangat dibutuhkan oleh setiap trader.",
      home_cont3: "Anda hanya perlu membuka akun Live untuk mendapatkan akses ke dalam pasar keuangan terbesar di dunia atau anda juga dapat membuka akun Demo untuk melatih kemampuan trading anda melalui aplikasi kami yang canggih, inovatif dan mudah digunakan",
      home_cont4: "Trading CFD memiliki risiko dan dapat menghilangkan modal anda",
      home_title4: "Follow",
      home_title5: "a Master",
      home_cont5: "Para Master di TigerWit merupakan master yang telah di seleksi dan diurut berdasarkan performa serta strategi trading mereka.",
      home_cont6: "Ikuti setiap langkah transaksi Master trader dan",
      home_cont7: "salin strategi mereka",
      home_cont8: "hanya dengan 1 klik.",
      home_cont9: "Ayo mulai dan unduh aplikasinya",
      home_title6: "Become",
      home_title7: "a Master",
      home_cont10: "Jadilah seorang Master di TigerWit dan",
      home_cont11: "dapatkan komisi sebesar 20%",
      home_cont12: "dari setiap investor yang mengikuti anda",
      home_cont13: "Ayo mulai dan unduh aplikasinya",
      home_title8: "Unduh aplikasinya sekarang juga",
      traders_title1: "Gak masalah jika anda adalah",
      traders_title2: "trader berpengalaman atau",
      traders_title2_2: "orang baru di TigerWit",
      traders_title3: "Kami telah menggabungkan teknologi mutakhir dengan kenyamanan trading",
      traders_title4: "untuk memastikan bahwa setiap pengguna kami dapat mengakses pasar dunia dengan",
      traders_title5: "mudah melalui aplikasi yang khusus didesain untuk semua trader.. Pilih copy-trading,",
      traders_title6: "serta komisi Master trader sangat mudah untuk diakses, transparan dan sederhana.",
      traders_cont1: "Trading FX secara global",
      traders_cont2: "Berbagai pilihan Pasar, bebas bertransaksi dengan metode apa saja",
      traders_cont3: "Pilihan copy-trading yang inovatif dan mudah digunakan",
      traders_cont4: "Teregulasi SCB dan FCA",
      traders_cont5: "Metode deposit dan penarikan yang efisien",
      traders_cont6: "Didukung oleh teknologi Blockchain",
      partners_title1: "Kami membangun kerjasama",
      partners_title2: "dan hubungan jangka panjang",
      partners_cont1: "Menjadi seorang mitra di TigerWit artinya anda menjadi bagian dari perusahaan dunia yang komit dalam membangun hubungan jangka panjang serta ikut membangun kesuksesan untuk setiap klien anda",
      partners_cont2: "Tidak ada platform trading lain selain kami yang memiliki teknologi blockchain trading ledger yang aman serta inovatif. Teknologi tersebut akan dimiliki oleh setiap klien anda melalui aplikasi kami yang sangat intuitif serta mudah untuk digunakan.",
      partners_join: "Gabung bersama kami",
      partners_block1_1: "Aplikasi kami memiliki",
      partners_block1_2: "fitur managemen",
      partners_block1_3: "akun yang sederhana",
      partners_block1_4: "dan mudah untuk digunakan",
      partners_block2_1: "Promosi ekslusif",
      partners_block2_2: "bersama mitra kami",
      partners_block2_3: "Klub Sepakbola",
      partners_block2_4: "Liverpool",
      partners_block3_1: "Teknologi",
      partners_block3_2: "blockchain yang",
      partners_block3_3: "bernama distributed",
      partners_block3_4: "trading ledger",
      partners_block4_1: "Dukungan penuh",
      partners_block4_2: "untuk para agen kami",
      partners_block4_3: "dukungan teknologi dan",
      partners_block4_4: "klien selama 24/5",
      partners_block5_1: "Teregulasi oleh",
      partners_block5_2: "SCB dan FCA"
    },
    mena: {
      open_account: "Open an account",
      live_account: "حساب تجريبي",
      demo_account: "افتح حساب حقيقي",
      navbar_home: "Home",
      navbar_traders: "Traders",
      navbar_partners: "Partners",
      home_title1: "تداول بمنتهى البساطة، إنسخ متداول محترف.",
      home_title2: "انضم إلى 250000 + من المتداولين",
      home_title3: "\"تيغرويت\"على",
      home_cont1: "اتبع محترفاً لنسخ تداولاتها والوصول إلى أسواق العملات الأجنبية العالمية من خلال تطبيقنا المميز.",
      home_cont2: " المفتاح لعالم جديد مثير من إمكانيات التداول ، لتجربة بسيطة وشفافة يستحقها كل متداول ",
      home_cont3: "افتح حسابًا حقيقيًا للوصول إلى الأسواق المالية الأكثر تداولًا في العالم أو يمكنك فتح حساب تجريبي لممارسة مهارات التداول الخاصة بك من خلال تطبيقنا البسيط",
      home_cont4: "ينطوي تداول عقود الفروقات على مخاطر ويمكن أن يؤدي إلى خسارة أموالك",
      home_title4: "اتبع متداول محترف",
      home_cont5: "يتم اختيار سادة \"تيغرويت\" وتصنيفهم بناءً على أدائهم واستراتيجيات التداول الخاصة بهم.",
      home_cont6: "اتبع متداول محترف بخطوات وكرر استراتيجيات بنقرة واحدة فقط",
      home_cont9: "قم بتحميل التطبيق و ابدأ التداول الآن",
      home_title6: "اصبح متداول محترف",
      home_cont10: "كن متداول محترف لدى \"تيغرويت\" واربح عمولة %20 على أرباح المتابعين لك",
      home_cont13: "قم بتحميل التطبيق و ابدأ التداول الآن",
      home_title8: "قم اليوم بتحميل التطبيق",
      traders_title1: "لا يهم إذا كان المتداول متمرسًا أو",
      traders_title2: "جديدًا مع \"تيغرويت\"",
      traders_title3: "لقد جمعنا بين أحدث التقنيات والراحة لضمان وصول المستخدمين إلى الأسواق العالمية من خلال تطبيق",
      traders_title4: " بسيط ومتطور مصمم خصيصًا لجميع المتداولين. خيارات النسخ بالتداول لدينا ، ولجان المتداولين",
      traders_title5: "الرئيسيين التنافسيين يمكن الوصول إليها وشفافة وبسيطة",
      traders_cont1: "تداول الفوركس على مستوى العالم",
      traders_cont2: "اختيارك للأسواق ، بالطريقة التي تريد التداول بها",
      traders_cont3: "خيارات نسخ التداول مبتكرة وسهلة المتابعة",
      traders_cont4: "إشراف ورقابة من جانب هيئة FCA و SCB",
      traders_cont5: "كفاءة الإيداع النقدي ووضع السحب",
      traders_cont6: "مدعوم من تقنية البلوكشين",
      partners_title1: "نبني شراكات قوية وعلاقات",
      partners_title2: "طويلة الأجل",
      partners_cont1: "كونك شريكًا في \"تيغرويت\" يعني أن تكون جزءًا من شركة عالمية تقوم بتطوير علاقات طويلة الأجل وتحتفل بنجاح العملاء",
      partners_cont2: "ما من منصة تداول أخرى تتمتع بتقنية البلوكشين, آمنة و مبتكرة و متوفرة في تطبيق سهل و بسيط",
      partners_join: "انضم إلينا",
      partners_block1_1: "وظائف إدارة الحساب بسيطة",
      partners_block1_2: "على تطبيق سهل الإستخدام",
      partners_block2_1: "عرض حصري مع",
      partners_block2_2: "شريكنا ليفربول",
      partners_block3_1: "ترتكز تقنية البلوكشي",
      partners_block3_2: "على كيفيّة توزع حسابات",
      partners_block3_3: "التداول المتوازي",
      partners_block4_1: "خطة دعم الوكالة",
      partners_block4_2: " المتقدمة",
      partners_block4_3: "24/5 دعم العملاء",
      partners_block4_4: " والتكنولوجيا",
      partners_block5_1: "إشراف ورقابة من جانب",
      partners_block5_2: "هيئة FCA و SCB  "
    },
    portuguese: {
      open_account: "Abrir uma conta",
      live_account: "Abra uma conta",
      demo_account: "Abra uma conta Demo",
      navbar_home: "Iniciar",
      navbar_traders: "Traders",
      navbar_partners: "Parceiros",
      home_title1: "Negociação simplificada, copy-trade com",
      home_title2: "um Mestre. Junte-se aos mais de 250.000",
      home_title3: "traders do TigerWit.",
      home_cont1: "Siga um trader mestre para copiar suas operações e acessar os mercados monetários globais em nosso aplicativo inteligente, simples e intuitivo.",
      home_cont2: "A chave para um mundo novo e emocionante de possibilidades de negociação para a experiência simples e transparente que os traders merecem.",
      home_cont3: "Abra uma conta ativa para acessar nos mercados financeiros mais importantes do mundo, ou você pode abrir uma conta Demo para praticar suas habilidades como trader em nosso aplicativo inteligente, inovador e fácil de usar.",
      home_cont4: "TradTrading de CFD envolve riscos e pode resultar na perda de seu capital",
      home_title4: "Siga",
      home_title5: "um Mestre",
      home_cont5: "Os traders TigerWit são selecionados e classificados com base em seu desempenho e estratégias de negócios.",
      home_cont6: "Siga as etapas de um Master Trader e copie suas estratégias com um único clique. ",
      home_cont7: "",
      home_cont8: "",
      home_cont9: "Começar e obter o aplicativo",
      home_title6: "Torne-se",
      home_title7: "um Mestre",
      home_cont10: "Torne-se um mestre em TigerWit e",
      home_cont11: "ganhe 20% de comissão",
      home_cont12: "nas operações de seus seguidores.",
      home_cont13: "Começar e obter o aplicativo",
      home_title8: "Baixar aplicativo agora",
      traders_title1: "Não importa se um profissional",
      traders_title2: "tem experiência ou está",
      traders_title2_2: "iniciando no TigerWit",
      traders_title3: "Combinamos tecnologia de ponta para garantir que os usuários possam",
      traders_title4: "acessar os mercados globais em um aplicativo simples e sofisticado",
      traders_title5: "que se adapta a todos os comerciantes. Nossas opções de negociação",
      traders_title6: "de cópias  e comissões competitivas do Master Trader são acessíveis,",
      traders_title6_2: "transparentes e simples.",
      traders_cont1: "Negocie FX globalmente",
      traders_cont2: "Sua escolha de mercados, a maneira como você deseja operar",
      traders_cont3: "Opções de negociação inovadoras e fáceis de seguir",
      traders_cont4: "Regulamentado por SCB e FCA",
      traders_cont5: "Modo eficiente de depósito e retirada de dinheiro",
      traders_cont6: "Acionado por blockchain",
      partners_title1: "Construímos uma forte parceria e",
      partners_title2: "um relacionamento de longo prazo",
      partners_cont1: "Ser parceiro da TigerWit significa fazer parte de uma empresa global que desenvolve um relacionamento de longo prazo e celebra o sucesso de nossos clientes.",
      partners_cont2: "Nenhuma outra plataforma de negociação possui nosso livro contábil blockchain seguro e inovador, que está disponível para seus clientes em um aplicativo intuitivo e fácil de usar.",
      partners_join: "Aderir",
      partners_block1_1: "Funções simples de",
      partners_block1_2: "gerenciamento de",
      partners_block1_3: "contas em um",
      partners_block1_4: "aplicativo fácil de usar",
      partners_block2_1: "Promoções exclusivas",
      partners_block2_2: "com nossos parceiros",
      partners_block3_1: "Livro de",
      partners_block3_2: "trading baseado",
      partners_block3_3: "em blockchain",
      partners_block4_1: "Plano de suporte",
      partners_block4_2: "antecipado da agência",
      partners_block4_3: "24/5 clientes e",
      partners_block4_4: "suporte tecnológico",
      partners_block5_1: "SCB e FCA",
      partners_block5_2: "regulado"
    },
    spanish: {
      open_account: "Abrir una cuenta",
      live_account: "Abrir una cuenta",
      demo_account: "Abrir una cuenta Demo",
      navbar_home: "Inicio",
      navbar_traders: "Traders",
      navbar_partners: "Socios",
      home_title1: "Trading simplificado, copy-trade con un",
      home_title2: "Master. Únete a los más de 250,000",
      home_title3: "traders en TigerWit.",
      home_cont1: "Sigue a un master trader para copiar sus operaciones y acceder a los mercados globales de divisas en nuestra aplicación inteligente, simple e intuitiva.",
      home_cont2: "La clave para un nuevo y emocionante mundo de posibilidades de negociación para la experiencia simple y transparente que los traders merecen.",
      home_cont3: "Abra una cuenta en vivo para acceder a los mercados financieros más importantes del mundo, o puede abrir una cuenta Demo para practicar sus habilidades  como trader en  nuestra aplicación inteligente, innovadora y fácil de usar.",
      home_cont4: "El trading de CFD implica riesgos y puede resultar en la pérdida de su capital",
      home_title4: "Siga a",
      home_title5: "un Master",
      home_cont5: "Los traders de TigerWit se seleccionan y clasifican en función de su rendimiento y estrategias comerciales.",
      home_cont6: "Siga los pasos de un Master Trader y copie sus estrategias con un solo click. ",
      home_cont9: "Descargar aplicación y comenzar",
      home_title6: "Conviértase en",
      home_title7: "un Master",
      home_cont10: "Conviértete en un maestro de TigerWit y gana un 20% de comisión en las operaciones de tus seguidores.",
      home_cont13: "Descargar aplicación y comenzar",
      home_title8: "Descargar aplicación ahora",
      traders_title1: "No importa si es un profesional",
      traders_title2: "que tiene experiencia o está",
      traders_title2_2: "comenzando en TigerWit",
      traders_title3: "Combinamos tecnología de punta para garantizar a los usuarios que",
      traders_title4: "acceden a los mercados globales en una aplicación simple y sofisticada",
      traders_title5: "que se adapta a todos los traders. Nuestras opciones de",
      traders_title6: "copy-trading y las comisiones competitivas de",
      traders_title6_2: "Master trader son accesibles, transparentes y simples.",
      traders_cont1: "Trade FX a nivel mundial",
      traders_cont2: "Su elección de mercados, la forma en que desea operar",
      traders_cont3: "Opciones de trading fáciles de copiar e innovadoras",
      traders_cont4: "Regulado por SCB e FCA",
      traders_cont5: "Modo eficiente de depósito y retiro de dinero",
      traders_cont6: "Impulsado por blockchain",
      partners_title1: "Construimos una asociación",
      partners_title2: "sólida y una relación a largo plazo",
      partners_cont1: "Ser socio de TigerWit significa ser parte de una compañía global que desarrolla una relación a largo plazo y celebra el éxito de nuestros clientes.",
      partners_cont2: "Ninguna otra plataforma de trading tiene nuestro libro mayor contable de blockchain seguro e innovador, que está disponible para sus clientes en una aplicación intuitiva y fácil de usar.",
      partners_join: "Únase",
      partners_block1_1: "Funciones simples",
      partners_block1_2: "de administración",
      partners_block1_3: "de cuentas en una",
      partners_block1_4: "aplicación fácil de usar",
      partners_block2_1: "Promocione exclusivas",
      partners_block2_2: "con nuestros socios",
      partners_block3_1: "Libro mayor",
      partners_block3_2: "contable de",
      partners_block3_3: "trading basado",
      partners_block3_4: "en blockchain",
      partners_block4_1: "Plan de apoyo anticipado",
      partners_block4_2: "de la agencia",
      partners_block4_3: "24/5 clientes y",
      partners_block4_4: "soporte tecnológico",
      partners_block5_1: "SCB y FCA",
      partners_block5_2: "regulado"
    },
    vietnam: {
      open_account: "Mở Tài Khoản",
      live_account: "Mở tài khoản thật",
      demo_account: "Tài khoản demo",
      navbar_home: "Trang Chủ",
      navbar_traders: "Nhà Giao Dịch",
      navbar_partners: "Đối Tác",
      home_title1: "Giao dịch đơn giản, sao chép giao dịch của",
      home_title2: "Chuyên Gia. Tham gia cùng hơn 250 000",
      home_title3: "người giao dịch trên TigerWit.",
      home_cont1: "Theo sau một Chuyên Gia để sao chép các giao dịch của họ và truy cập vào thị trường Ngoại Hối toàn cầu trên ứng dụng thông minh, đơn giản và trực quan của chúng tôi.",
      home_cont2: "Chìa khóa  để vào một thế giới giao dịch thú vị đầy tiềm năng, cho những trải nghiệm đơn giản , minh bạch mà mọi nhà giao dịch đều xứng đáng.",
      home_cont3: "Mở tài khoản thật để truy cập vào các thị trường tài chính được giao dịch nhiều nhất trên thế giới hoặc bạn có thể mở tài khoản trải nghiệm để thực hành các kỹ năng giao dịch của mình trên ứng dụng thông minh, sáng tạo và dễ sử dụng của chúng tôi.",
      home_cont4: "Giao dịch CFDs có thể rủi ro đến nguồn vốn của bạn",
      home_title4: "Theo bước",
      home_title5: "Chuyên gia",
      home_cont5: "Các chuyên gia TigerWit được chọn và xếp hạng dựa trên chiến lược giao dịch và thành tích của họ.",
      home_cont6: "Theo bước  của một nhà giao dịch bậc thầy và",
      home_cont7: "sao chép chiến lược của",
      home_cont8: "họ chỉ bằng một cú nhấp chuột.",
      home_cont9: "Bắt đầu tải ứng dụng ngay",
      home_title6: "Hãy trở thành",
      home_title7: "một Chuyên gia",
      home_cont10: "Hãy trở thành một chuyên gia TigerWit và",
      home_cont11: "kiếm 20% hoa hồng",
      home_cont12: "từ các giao dịch dõi theo bạn.",
      home_cont13: "Bắt đầu tải ứng dụng ngay",
      home_title8: "Tải ứng dụng ngay hôm nay",
      traders_title1: "TigerWit luôn đồng hành cùng các",
      traders_title2: "nhà giao dịch mới cũng như đã",
      traders_title2_2: "có kinh nghiệm trên thị trường",
      traders_title3: "Chúng tôi đã kết hợp sự tiến bộ công nghệ và sự tiện ích để đảm bảo cho người",
      traders_title4: "dùng có thể truy cập và điều chỉnh ứng dụng giao dịch thị trường tài chính toàn cầu",
      traders_title5: "một cách đơn giản và tinh vi nhất. Việc tùy chọn sao chép giao dịch của chúng",
      traders_title6: "tôi cũng như hoa hồng cạnh tranh của các chuyên gia giao dịch sẽ",
      traders_title6_2: "được truy cập, đơn giản và minh bạch.",
      traders_cont1: "Giao dịch ngoại hối toàn cầu",
      traders_cont2: "Hãy giao dịch trong thị trường bạn muốn",
      traders_cont3: "Quyền chọn Copy-trading đơn giản, sáng tạo",
      traders_cont4: "Theo quy định SCB và FCA",
      traders_cont5: "Gửi và rút tiền nhanh chóng, hiệu quả",
      traders_cont6: "Nền tảng công nghệ BlockChain",
      partners_title1: "Chúng tôi xây dựng mối quan",
      partners_title2: "hệ hợp tác bền vững và",
      partners_title2_2: "phát triển lâu dài",
      partners_cont1: "Trở thành đối tác của TigerWit nghĩa là bạn tham gia vào hệ thống toàn cầu của chúng tôi nhằm phát triển mối quan hệ bền chặt và tôn vinh thành công từ các khách hàng của bạn",
      partners_cont2: "Nền tảng giao dịch blockchain an toàn, sáng tạo cùng với ứng dụng đơn giản, trực quan cho khách hàng của bạn",
      partners_join: "Tham gia cùng chúng tôi",
      partners_block1_1: "Chức năng quản lý tài",
      partners_block1_2: "khoản đơn giản hơn và",
      partners_block1_3: "dễ dàng hơn trên ứng",
      partners_block1_4: "dụng giao dịch",
      partners_block2_1: "Được nhận những",
      partners_block2_2: "khuyến mãi đặc biệt từ",
      partners_block2_3: "đối tác LiverPool FC",
      partners_block2_4: "của chúng tôi",
      partners_block3_1: "Hồ sơ giao",
      partners_block3_2: "dịch được phân",
      partners_block3_3: "bổ dựa trên nền",
      partners_block3_4: "tảng Blockchain",
      partners_block4_1: "Được hỗ trợ kế hoạch",
      partners_block4_2: "phát triển đại lý",
      partners_block4_3: "Hỗ trợ khách hàng và",
      partners_block4_4: "hỗ trợ công nghệ",
      partners_block5_1: "Theo quy định",
      partners_block5_2: "SCB và FCA"
    }
  };
  if ($(".bd_forextrading").attr("data-mobile") === '1') {
    $(".bd_open_account").attr("href", "/download");
    $(".bd_live_account").attr("href", "/download");
    $(".bd_demo_account").attr("href", "/download");
  }
  console.log(page);
  page = pageInfo[page] ? page : "english";
  for (var i in pageInfo[page]) {
    $(".bd_"+i).html(pageInfo[page][i]);
  }
  if (page === 'mena') {
    $(".bd_forextrading").attr("dir", "rtl");
    $(".bd_forextrading .bd_live_account").removeClass("mg-rg-80").addClass("mg-lf-80");
    $(".download_btn_wrapper a:first-child").css({
      marginRight: "0px",
      marginLeft: "25px"
    });
    $(".home_focus2_pic").css({
      marginLeft: "0px",
      marginRight: "120px"
    });
    $(".home_focus2_content").css({
      marginLeft: "0px",
      marginRight: "70px"
    });
  }
})();